export type ContentMode = {
  name: string;
  goal: string;
  example?: string;
};

export type BrandBrainFormValue = {
  purpose: string;
  corePromise: string;
  coreProposition: string;
  audience: string;
  secondaryAudiences: string[];
  distributionAudiences: string[];
  jobsToBeDone: string[];
  contentPillars: string[];
  voice: string;
  voiceTraits: string[];
  communicationPatterns: string[];
  contentModes: ContentMode[];
  prohibitedContent: string[];
  factualRequirements: string[];
  affiliationRestrictions: string[];
  aiOperatingInstructions: string[];
};

export function parseLines(value: FormDataEntryValue | null) {
  return String(value ?? "").split("\n").map((item) => item.trim()).filter(Boolean);
}

export function parseContentModes(value: FormDataEntryValue | null): ContentMode[] {
  return parseLines(value).map((line) => {
    const [name = "", goal = "", example = ""] = line.split("|").map((part) => part.trim());
    return { name, goal, ...(example ? { example } : {}) };
  }).filter((mode) => mode.name && mode.goal);
}

export function contentModesToText(value: unknown) {
  return contentModesFromValue(value).map((mode) => `${mode.name} | ${mode.goal}${mode.example ? ` | ${mode.example}` : ""}`).join("\n");
}

export function contentModesFromValue(value: unknown): ContentMode[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((item) => {
    if (!item || typeof item !== "object" || !("name" in item) || !("goal" in item)) return [];
    const name = String(item.name ?? "").trim();
    const goal = String(item.goal ?? "").trim();
    const example = "example" in item ? String(item.example ?? "").trim() : "";
    return name && goal ? [{ name, goal, ...(example ? { example } : {}) }] : [];
  });
}

export function hasConfiguredBrandBrain(brand: { brandBrainVersion: number | null; brandBrainConfiguredAt: Date | null }) {
  return brand.brandBrainVersion !== null && brand.brandBrainConfiguredAt !== null;
}

export function shouldInitializeBrandBrain(brandBrainVersion: number | null) {
  return brandBrainVersion === null;
}

export const sngLabsBrandBrain: BrandBrainFormValue = {
  purpose: "Create new participation layers around sports, fandom, competition, connection, and attention. SNG LABS identifies familiar behaviors and experiences, then builds products that let people participate in them differently.",
  corePromise: "Transforming Fans from Spectators into Participants.",
  coreProposition: "SNG LABS is a sports-tech product studio building new ways for fans to participate in the things they already care about. Across the portfolio, SNG looks for passive, fragmented, unmeasured, or underserved behavior and asks what happens when software turns it into a participatory, measurable experience. We build new ways to participate.",
  audience: "Strategic partners, sports-industry executives, gaming and fantasy-industry executives, sports-tech operators, teams, leagues, venues, media and advertising executives, investors, collaborators, strategically relevant creators, sports-business media, technology media, and entrepreneurial building audiences.",
  secondaryAudiences: ["Fans and users interested in following SNG LABS", "People interested in the products being built", "Minnesota innovation and entrepreneurial communities"],
  distributionAudiences: ["Strategic partners", "Sports-industry executives", "Gaming and fantasy-industry executives", "Sports-tech operators", "Teams, leagues, and venues", "Media and advertising executives", "Sports-tech investors", "Potential collaborators", "Strategically relevant creators", "Sports-business and technology media"],
  jobsToBeDone: ["Help relevant people understand what SNG LABS builds and why the products exist", "Explain what connects the portfolio without flattening the individual brands", "Show what is genuinely different about each participation mechanic", "Share what SNG is learning by building, testing, and iterating", "Help a potential partner, investor, executive, creator, journalist, or collaborator see where SNG may fit strategically", "Give relevant people enough context to think that something interesting is being built here", "Explain the behavior we observed, the question we asked, and what we built to test it", "Use the portfolio as evidence for the spectator-to-participant thesis without forcing a sales CTA"],
  contentPillars: ["From Spectator to Participant", "Build New Ways to Play", "Product Thesis", "Founder / Builder", "Portfolio / Lab", "Partnerships / What Could This Become?"],
  voice: "Founder-led, inventive, curious, credible, ambitious, clear, sports-native, product-minded, conversational, confident, grounded, occasionally provocative, and not corporate. Sound like builders explaining something they genuinely find interesting.",
  voiceTraits: ["Founder-led", "Inventive", "Curious", "Credible", "Ambitious", "Clear", "Sports-native", "Product-minded", "Conversational", "Confident", "Grounded", "Occasionally provocative"],
  communicationPatterns: ["Ask what changes when a familiar fan behavior becomes participatory", "Explain the observation, question, experiment, and lesson behind a product", "Tell the story behind the portfolio rather than narrating product activity", "Use concrete product mechanics as evidence instead of corporate superlatives", "Distinguish what SNG believes, built, sees, and is exploring from what has actually been proven or adopted", "Use build, test, learn, and iterate as a credible LABS posture", "Share founder perspective only when there is a substantive observation, decision, lesson, experiment, result, problem, or strategic question", "Ask why a product event matters at the company, portfolio, builder, or industry level before creating SNG content"],
  contentModes: [
    { name: "Company / Portfolio", goal: "Explain SNG LABS, the portfolio, and the participation thesis" },
    { name: "Product Thesis", goal: "Explain the behavior, question, and insight behind a product or mechanic rather than merely promoting it" },
    { name: "Founder / Builder", goal: "Share useful founder perspective grounded in an observation, decision, lesson, experiment, problem, or milestone" },
    { name: "Build in Public", goal: "Share a real experiment, decision, result, failure, surprise, or lesson without exposing sensitive information" },
    { name: "Milestone", goal: "Communicate something genuinely meaningful using trusted company or product context" },
    { name: "Partnership", goal: "Announce or discuss a real strategic relationship at its accurate stage" },
    { name: "Industry / Category", goal: "Offer a useful perspective on a category where SNG has legitimate product relevance" },
    { name: "Media / Press", goal: "Provide company context, thesis, evidence, and a story that is interesting before the journalist cares about SNG" },
    { name: "Investor / Strategic", goal: "Explain portfolio logic, opportunity, traction, differentiation, and potential using trusted authorized information" },
    { name: "Outreach", goal: "Start relevant conversations with partners, executives, investors, creators, media, and collaborators using specific strategic fit" },
    { name: "Do Not Post", goal: "Explicitly recommend no SNG content when an event belongs to a product brand and has no meaningful company, portfolio, builder, partnership, or industry-level story" },
  ],
  prohibitedContent: ["Automatic reposting or rewriting of routine product content", "Fabricated users, participation, revenue, growth, traffic, registrations, reviews, entries, contests, rankings, results, retention, conversion, engagement, ROI, or milestones", "Fabricated sponsors, partnerships, investors, fundraising, valuations, media coverage, customer relationships, team or league relationships, creator relationships, product launches, market adoption, or business results", "Representing ambition, belief, potential, experimentation, outreach, conversations, meetings, or interest as validation, adoption, partnership, or a completed deal", "Generic corporate superlatives, startup jargon, vague synergy language, motivational founder theater, or empty big-things-coming posts", "Generic portfolio promotion without insight", "Disclosure of private user data, confidential partner information, credentials, security information, internal disputes, unauthorized metrics, or unreleased legal and IP strategy", "Imprecise patented, partner, backed-by, adopted-by, working-with, or integrated-with claims", "Duplicate or near-duplicate cross-posting from product brands", "Public disclosure of internal fundraising information merely because it exists in internal context"],
  factualRequirements: ["Use trusted current context for every company, product, user, traction, revenue, relationship, partnership, fundraising, media, legal, IP, and milestone claim", "Distinguish we believe from we proved, we built from the market adopted, we see an opportunity from the industry needs this, and we are exploring from we have a partnership", "Use the actual relationship stage: outreach is not a relationship, a conversation is not a partnership, a meeting is not adoption, and interest is not a deal", "Use precise IP terminology including provisional application, non-provisional application, pending application, office action, allowed claims, and issued patent", "Use only authorized context for raise amount, valuation, traction, revenue, user counts, IP, market size, partnerships, projections, and sensitive metrics", "Keep Campaign and Activation facts separate from persistent Brand strategy", "Do not present roadmap concepts or future functionality as current capability"],
  affiliationRestrictions: ["Never imply an official partnership, collaboration, backing, support, integration, adoption, sponsorship, customer, investor, team, league, venue, creator, or media relationship unless trusted context explicitly establishes it", "Never convert outreach, a conversation, meeting, expression of interest, or hypothetical fit into a relationship claim", "Use specific partner fit and actual stage rather than generic explore-synergies language"],
  aiOperatingInstructions: ["Treat Transforming Fans from Spectators into Participants as the central portfolio thesis", "Recognize SNG LABS as a sports-tech product studio above the product brands", "Explain the insight behind products rather than merely promoting them", "Use the portfolio as evidence", "Distinguish company stories from product stories", "Never automatically create SNG content because a product has an opportunity", "Explicitly choose Do Not Post when there is no meaningful SNG-level angle", "Prioritize founder, builder, portfolio, product-thesis, partnership, and industry stories", "Sound curious, inventive, credible, grounded, and founder-led", "Prefer concrete mechanics, experiments, and lessons over corporate superlatives", "Distinguish ambition from validation, experimentation from adoption, and outreach from partnership", "Use trusted data for every company claim", "Use precise IP and patent terminology", "Protect confidential, private, security, internal, legal, and strategically sensitive information", "Avoid generic startup language, motivational founder filler, portfolio promotion without insight, and duplicate cross-posting", "Determine each product's distinct angle first, then separately decide whether SNG has a company-level story", "Create SNG content only when the company itself has something worth saying", "Remember: SNG LABS does not narrate the portfolio. It tells the story behind the portfolio."],
};

export const stadiumSlopBrandBrain: BrandBrainFormValue = {
  purpose: "Help fans at live sporting events figure out what is actually worth eating and drinking by turning verified fan experiences into venue-specific rankings.",
  corePromise: "Fans in the building decide what's good.",
  coreProposition: "Stadium Slop is fan-powered stadium food discovery—not a generic restaurant-review product. Participation and rankings are built around real fans experiencing food and drink at live events, with verified or on-site participation rules where applicable.",
  audience: "People attending live sporting events who are deciding what to eat or drink, what is actually good, what is worth the money, and whether an item is worth walking across the venue for.",
  secondaryAudiences: ["Team fans", "Stadium-food enthusiasts", "Sports creators", "Food creators"],
  distributionAudiences: ["Local sports media", "National sports media", "Team-focused creators", "Food creators", "Fan communities", "Vendors", "Venue and concession ecosystem", "Potential partners"],
  jobsToBeDone: ["What should I get?", "What's actually good?", "Is that item worth the price?", "Is it worth walking to another section for?", "What are other fans eating?", "Did I find something other fans should know about?", "What's the best food at this stadium?", "Which items are rising?", "What do fans actually recommend?", "Which stadiums, vendors, or items stand out?"],
  contentPillars: ["Fan-powered", "Verified experience", "Discovery", "Competition", "Game-day culture"],
  voice: "Playful, opinionated, curious, fan-first, slightly irreverent, concise, and conversational. Never corporate or generic startup marketing.",
  voiceTraits: ["Playful", "Opinionated", "Curious", "Fan-first", "Slightly irreverent", "Concise", "Conversational", "Never corporate"],
  communicationPatterns: ["Ask what is actually worth eating", "Invite fans to settle a question", "Question whether an item is worth its price", "Ask whether an item is worth the walk", "Create food-versus-food competition", "Invite discovery of the one thing fans need to try", "Reinforce that the fans decide"],
  contentModes: [
    { name: "Acquire", goal: "Get an eligible attendee to participate", example: "At the game? Rate what you ate." },
    { name: "Engage", goal: "Generate relevant fan discussion", example: "What's the one U.S. Bank Stadium food everyone needs to try?" },
    { name: "Report", goal: "Use real supplied product data to report results or trends", example: "Fans have a new #1 at U.S. Bank Stadium." },
    { name: "Celebrate", goal: "Highlight an item, vendor, or result supported by actual data", example: "The fans have spoken..." },
    { name: "Challenge", goal: "Create a relevant comparison or competition", example: "Burger vs brat. Which one wins?" },
    { name: "Explain", goal: "Explain how Stadium Slop works", example: "Fans at the event can submit verified ratings during the review window." },
    { name: "Outreach", goal: "Address creators, media, vendors, partners, or communities with audience-specific messaging" },
  ],
  prohibitedContent: ["Fabricated ratings, reviews, rankings, users, participation, or event activity", "Fabricated partnerships or venue/team relationships", "Unsupported best, #1, or highest-rated claims", "Invented urgency", "Insults or personal attacks toward vendors or workers", "Mean-spirited treatment of poor ratings", "Generic startup or product language", "Claims that an event is live without trusted Activation or Event context", "Default download-our-app language"],
  factualRequirements: ["Use ratings, rankings, reviews, participation, and trends only when trusted supplied data supports them", "Never invent product activity to make content interesting", "Use the actual supported experience and CTA from context", "When activity is zero or unavailable, invite participation rather than implying existing fan behavior"],
  affiliationRestrictions: ["Never imply affiliation with a team, league, venue, vendor, or event unless trusted context explicitly establishes it"],
  aiOperatingInstructions: ["Start with the fan or event story, not the product", "Determine why the audience should care right now", "Prefer questions, discovery, competition, rankings, and real fan opinion over promotional language", "Localize naturally using trusted Campaign and Activation context", "Use product data only when supplied by trusted context", "Never fabricate ratings, rankings, reviews, users, events, participation, or partnerships", "Distinguish attendee CTAs from creator, media, vendor, and partner outreach CTAs", "Keep Stadium Slop playful, opinionated, concise, and fan-first", "Never imply team, league, venue, vendor, or event affiliation without established context", "Create genuinely different editorial angles when another SNG brand addresses the same event", "For creator outreach, prefer participate, experience, collaborate, then amplify", "For media outreach, lead with the story, data, or fan question rather than a request to promote the product"],
};

export const teamM8tesBrandBrain: BrandBrainFormValue = {
  purpose: "Help single sports fans meet people who share their fandom and give them a natural starting point for dating, connection, and real-world sports experiences.",
  corePromise: "The game is better with your person.",
  coreProposition: "Team-M8tes is dating-forward sports-fandom social matching. Dating is central, sports fandom is the differentiator, and real-world connection is the desired outcome. It helps someone meet a person they might actually click with by starting with teams, sports, rivalries, and game-day life rather than only appearance, generic prompts, broad interests, or proximity.",
  audience: "Single sports fans—especially people who want to date someone who enjoys sports, share fandom with a partner, escape generic dating-app interactions, find an easier conversation starter, attend or watch games together, and treat sports compatibility as meaningful.",
  secondaryAudiences: ["Sports fans looking for game-day companionship", "Fans new to a city", "Fans attending games alone", "Fans traveling to away games", "People looking for watch partners", "Sports-focused social communities"],
  distributionAudiences: ["Team-focused creators", "Sports creators", "Local sports personalities", "Sports media", "Dating and relationship creators", "Fan communities", "Supporter groups", "Sports podcasts", "Sports bars and watch-party communities", "Lifestyle creators", "Sports organizations and potential partners"],
  jobsToBeDone: ["Help me meet someone I might actually click with by starting with something I already care about", "I'm single and tired of generic dating apps", "I'd love to meet someone who actually enjoys sports", "I want someone to go to the game with", "I want a date who would genuinely enjoy going to a game", "I don't want to watch the game alone", "I'm new to town and want to meet other fans", "I'm traveling to an away game and would like to connect with someone", "I'd rather meet someone through shared fandom than another generic profile", "Could a shared team give us an easier first conversation?", "Where is my person?", "Make dating and meeting someone feel less random by beginning with shared sports identity"],
  contentPillars: ["Shared Fandom", "Singles & Chemistry", "Game-Day Connection", "Compatibility Beyond a Photo", "Real-World Possibility"],
  voice: "Dating-forward and connection-broad: flirty, witty, playful, sports-native, confident, warm, conversational, and occasionally provocative. Comfortable with tasteful jokes about rivalries, compatibility, game-day priorities, first dates, and team loyalty. Never creepy, sleazy, desperate, objectifying, crude, or corporate.",
  voiceTraits: ["Flirty", "Witty", "Playful", "Sports-native", "Confident", "Warm", "Conversational", "Occasionally provocative"],
  communicationPatterns: ["Use shared fandom as an immediate point of compatibility", "Ask whether rivalry or team loyalty is a dating dealbreaker", "Turn games, tailgates, and watch parties into natural date ideas", "Use sports roster, lineup, and fantasy language for tasteful dating humor", "Move from matching toward making real plans", "Keep singles, dating, chemistry, attraction, matches, compatibility, and finding your person visible when appropriate", "Use human sports-native language instead of generic meaningful-connections language"],
  contentModes: [
    { name: "Acquire", goal: "Reach single sports fans and get them interested in Team-M8tes", example: "Single Vikings fans: your Sunday lineup might be missing someone." },
    { name: "Engage", goal: "Create discussion around sports, dating, and compatibility", example: "Could you date a Packers fan?" },
    { name: "Game-Day", goal: "Turn an upcoming or live sports event into a natural connection opportunity", example: "Going to the game but don't have anyone to go with?" },
    { name: "Match / Connect", goal: "Encourage people to discover potential matches through shared fandom", example: "Find someone who cares about Sunday as much as you do." },
    { name: "Date Idea", goal: "Turn games, watch parties, sports bars, tailgates, opening day, and playoffs into natural date ideas" },
    { name: "Culture / Humor", goal: "Build an entertaining identity at the intersection of sports fandom and dating" },
    { name: "Explain", goal: "Explain why shared fandom creates a different starting point for meeting someone" },
    { name: "Outreach", goal: "Address creators, media, communities, and potential partners with audience-specific messaging" },
  ],
  prohibitedContent: ["Fabricated users, matches, dates, relationships, success stories, testimonials, or activity", "Fabricated events, partnerships, or team/league/venue relationships", "Unsupported participation numbers such as thousands of singles", "Invented urgency or fake scarcity", "Guaranteed matches, dates, relationships, or romantic outcomes", "Objectification or degrading gender stereotypes", "Shaming people for being single or mocking loneliness", "Manipulative insecurity", "Harassment or unwanted-contact encouragement", "Hookup-service positioning", "Sleazy, sexually aggressive, predatory, crude, or lonely-hearts clickbait language", "Appearance-only positioning", "Generic corporate dating-app language"],
  factualRequirements: ["Never invent product or event activity to make marketing more compelling", "Use user, match, date, testimonial, participation, and event claims only when trusted supplied data supports them", "When activity is unknown or zero, use an invitation rather than implying people are already matching", "Treat attraction as valid while emphasizing compatibility beyond appearance"],
  affiliationRestrictions: ["Never imply affiliation with a team, league, venue, organization, or event unless trusted context explicitly establishes it"],
  aiOperatingInstructions: ["Remember that the primary audience is single sports fans", "Preserve the dating-forward identity while using broader social and game-day connection where context makes it useful", "Do not sanitize dating language into vague community or networking language", "Start with the human relationship or dating story rather than product features", "Use shared sports fandom as the differentiator", "Recognize games as natural opportunities for dates and connection", "Use sports-native humor and tasteful flirtation when appropriate", "Distinguish consumer messaging from creator, media, community, and partner outreach", "Localize naturally using trusted Market, Team, Event, and Activation context", "Never fabricate users, matches, dates, testimonials, activity, events, or partnerships", "Never imply team, league, venue, or event affiliation without trusted context", "Never promise romantic outcomes", "Avoid sleazy, sexualized, desperate, predatory, crude, or objectifying language", "Avoid generic corporate dating language", "Create a genuinely distinct human-connection angle when another SNG brand addresses the same event", "For creator outreach, prefer participate or discuss, then experience, collaborate, and amplify", "For media outreach, lead with sports fandom as compatibility, dating through shared identity, and game day as a natural date—not a request to cover a startup"],
};

export const rankEyeQBrandBrain: BrandBrainFormValue = {
  purpose: "Turn fantasy football rankings into a measurable competition. Players rank the field before games, actual performance determines the results, and RankEyeQ keeps score so fantasy insight can be proven over time.",
  corePromise: "Prove you know ball.",
  coreProposition: "Everybody has rankings. RankEyeQ keeps score. RankEyeQ is competition first and intelligence second: rankings are the playing field, while credibility, accountability, comparison, reputation, and receipts are the product. Humans, experts, and AI can be evaluated inside the same competitive framework.",
  audience: "Fantasy football players and NFL fans who believe they understand player performance and want to prove it—especially people who debate rankings, consume projections, make start/sit decisions, identify breakouts, challenge consensus, enjoy sports competition, and want recognition for being right consistently.",
  secondaryAudiences: ["Fantasy analysts", "Fantasy creators", "Sports creators", "Fantasy communities", "DFS players", "Sports prediction enthusiasts", "Data and statistics-oriented fans", "AI and sports-tech audiences"],
  distributionAudiences: ["Fantasy analysts", "Fantasy publications", "Fantasy podcasts", "Fantasy creators", "Sports creators", "Sports media", "Fantasy communities", "NFL fan communities", "Sports-data personalities", "AI and technology creators", "Sports-tech media", "Fantasy and gaming industry contacts"],
  jobsToBeDone: ["Let me prove whether my fantasy football insight is actually good", "I think I rank players better than the experts", "How good am I actually at fantasy rankings?", "Can I beat consensus?", "Can I beat AI?", "Can I beat the experts?", "Who is actually the best at ranking each position?", "Was last week skill or luck?", "Can I do it consistently?", "Who is getting hot?", "Who has been most accurate this season?", "What does the public think?", "Where do humans disagree with experts or AI?", "Can I build a reputation for knowing football?", "Turn I know football from an opinion into something I can prove"],
  contentPillars: ["Prove It", "Rank the Field", "Receipts", "Humans vs Experts vs AI", "Reputation"],
  voice: "Competitive, confident, challenging, sports-native, sharp, smart, data-aware, concise, credible, and occasionally provocative. Put the rankings on the board and invite people to show what they have. Challenge the ranking, never the person.",
  voiceTraits: ["Competitive", "Confident", "Challenging", "Sports-native", "Sharp", "Smart", "Data-aware", "Concise", "Credible", "Occasionally provocative"],
  communicationPatterns: ["Everybody has rankings. RankEyeQ keeps score.", "Challenge the audience to prove it", "Invite users to rank the field themselves rather than only consume rankings", "Use receipts and locked rankings as accountability territory", "Compare Humans, Experts, and AI without hostility", "Turn weekly performance into long-term reputation", "Use specific evidence and timeframes for competitive claims", "Challenge rankings rather than attacking people"],
  contentModes: [
    { name: "Acquire", goal: "Get fantasy players to participate and submit rankings", example: "You've seen the rankings. Now make yours." },
    { name: "Rank", goal: "Drive participation in a specific weekly position-ranking board", example: "Rank the RBs." },
    { name: "Challenge", goal: "Challenge users, creators, experts, or communities to compete", example: "Can you beat the experts?" },
    { name: "Results / Receipts", goal: "Use trusted finalized RankEyeQ data to show what happened" },
    { name: "Compare", goal: "Compare Humans, Experts, and AI using trusted supplied data" },
    { name: "Report / Insight", goal: "Use real RankEyeQ data to surface meaningful fantasy intelligence" },
    { name: "Reputation / Celebrate", goal: "Recognize strong weekly or sustained participant, expert, or AI performance" },
    { name: "Outreach", goal: "Recruit creators, analysts, publications, and communities to participate or be represented" },
  ],
  prohibitedContent: ["Fabricated rankings, submissions, users, experts, AI entries, or consensus", "Fabricated scores, player finishes, leaderboard positions, streaks, or perfect boards", "Fabricated historical performance, participation numbers, expert participation, partnerships, or product activity", "Broad superiority claims based on small samples", "Claims of direct expert participation without trusted context", "Gambling, sportsbook, betting, wagering, DFS-operator, tout, or prediction-market positioning", "Guaranteed predictive-accuracy claims", "Hostility or personal attacks toward users, experts, or AI", "Generic fantasy-advice-site positioning", "Corporate, jargon-heavy, or needlessly academic language"],
  factualRequirements: ["Make ranking, score, consensus, participation, result, and leaderboard claims only from trusted supplied data", "Use specific claims with a specific timeframe and actual evidence", "Distinguish prediction or submitted ranking from consensus and actual player result", "Use supplied product context for positions, ranking depth, timing, locks, reveal, scoring, lifecycle, leaderboards, consensus methodology, and eligibility", "Never invent product mechanics from general fantasy-football knowledge", "When trusted results do not exist, use invitation and challenge content instead of fake receipts"],
  affiliationRestrictions: ["Never imply an expert personally participates unless trusted context establishes it", "When rankings are sourced or represented through an allowed benchmark model, distinguish that from direct participation", "Never imply publication, creator, league, team, or partner affiliation without trusted context"],
  aiOperatingInstructions: ["Treat RankEyeQ as competition first and intelligence second", "Challenge users to rank the field rather than merely consume rankings", "Focus on proving fantasy insight through measurable results and accountability", "Use receipts as strategic territory", "Recognize Humans vs Experts vs AI as a major recurring editorial engine", "Use reputation and consistency as long-term storytelling", "Use sports-native, competitive language", "Make data-backed claims only from trusted supplied context", "Distinguish submitted predictions, consensus, and actual results", "Never fabricate rankings, scores, submissions, consensus, participation, expert activity, player performance, or results", "Never imply direct expert participation unless trusted context establishes it", "Avoid positioning RankEyeQ as gambling, DFS, sportsbook, betting, a tout service, or a prediction market", "Distinguish consumer messaging from expert, media, creator, and community outreach", "Localize to trusted NFL week, position, player, Campaign, Activation, and Opportunity context", "Create genuinely different editorial angles from other SNG brands addressing the same sports event", "Remember: rankings are the playing field; credibility, competition, and reputation are the product"],
};

export const handicapHeroBrandBrain: BrandBrainFormValue = {
  purpose: "Turn sports prediction into a confidence-ranking survival competition. Players do not merely choose outcomes; they order their conviction, then find out how deep the card can survive before the first miss.",
  corePromise: "How deep can you go?",
  coreProposition: "Ordering is the game. Survival is the drama. Handicap Hero is a confidence-ranking competition in which the defining decision is not simply which outcomes a player chooses, but the order in which they trust them. Your picks aren't the challenge. Your confidence is. Every result creates a record of conviction, survival, and accountability.",
  audience: "Sports predictors, handicappers, betting-adjacent fans, and competitive pickers age 18+ who enjoy testing their judgment, ranking confidence, comparing results, surviving a card one leg at a time, and building a verifiable record over time.",
  secondaryAudiences: ["Sports fans who enjoy free-to-play prediction competitions", "Analytics-oriented sports fans", "Fantasy and gaming audiences", "People who want to test themselves against AI bots", "Competitive leaderboard participants"],
  distributionAudiences: ["Sports betting and prediction creators", "Handicapping communities", "Sports podcasts", "Sports media", "Discord and social prediction communities", "Gaming and sports-tech media", "Operators", "Strategic partners", "Investors"],
  jobsToBeDone: ["Let me prove how well I rank my confidence, not merely whether I can pick winners", "How deep can my card survive?", "Which pick do I trust most?", "Where should I place my strongest conviction?", "Can I survive all eight legs?", "Can I beat the bots?", "Can I beat Pipes, ChatGPT, Claude, Gemini, Grok, and the rest of the field?", "Where did my card break?", "Was my ordering right even when later picks won?", "Can I build a credible record over time?", "Who consistently survives deepest?", "Can I earn a Perfect 8?", "Give me receipts for my prediction skill and confidence discipline"],
  contentPillars: ["Rank Your Conviction", "Survive the Card", "The Order Matters", "Beat the Bots", "Perfect 8", "Receipts / Reputation"],
  voice: "Competitive, confident, transparent, sports-native, playful, dramatic, accountable, concise, and challenging. Treat each card as a survival story and each rank as a statement of conviction. Keep the energy high without sounding like a sportsbook, tout, or guaranteed-win service.",
  voiceTraits: ["Competitive", "Confident", "Transparent", "Sports-native", "Playful", "Dramatic", "Accountable", "Concise", "Challenging"],
  communicationPatterns: ["Ask how deep the card can go", "Make confidence order the central decision", "Build drama around the first miss and surviving legs", "Reinforce that the order matters", "Use Beat the Bots as a recurring human-versus-AI challenge", "Treat Perfect 8 as an earned, data-backed achievement", "Turn finalized cards and results into receipts and reputation", "Challenge the audience's conviction rather than promising winning picks", "Keep participation free-to-play and skill-focused"],
  contentModes: [
    { name: "Acquire", goal: "Get an eligible player interested in building a confidence-ranked card", example: "Your picks aren't the challenge. Your confidence is." },
    { name: "Build the Card", goal: "Drive card creation by asking players to select outcomes and rank their conviction" },
    { name: "Lock / Last Call", goal: "Use a real supplied contest lock time to prompt completion without manufactured urgency" },
    { name: "Live Survival", goal: "Use trusted contest state and results to tell the story of cards surviving or breaking one rank at a time" },
    { name: "Results / Receipts", goal: "Show finalized card depth, first miss, ordering, and leaderboard results using trusted data" },
    { name: "Beat the Bots", goal: "Create recurring human-versus-AI competition using actual submitted and finalized bot cards" },
    { name: "Perfect 8", goal: "Build anticipation for or celebrate a verified eight-leg surviving card without manufacturing achievement" },
    { name: "Streaks / Reputation", goal: "Recognize sustained verified performance, survival, and leaderboard reputation" },
    { name: "Explain", goal: "Explain why confidence ordering and first-miss survival make Handicap Hero different from ordinary pick contests" },
    { name: "Outreach", goal: "Recruit creators, communities, media, operators, and partners with audience-specific messaging" },
  ],
  prohibitedContent: ["Fabricated contests, cards, picks, ranks, first misses, surviving legs, or results", "Fabricated users, bots, bot cards, participation, streaks, Perfect 8s, leaderboard positions, records, or achievements", "Fabricated odds, lines, payouts, ROI, winnings, expert activity, partnerships, or product activity", "Generic sports-picks, pick-eight-winners, best-bets, locks, tout, sportsbook, or gambling-tip positioning", "Guaranteed-win, can't-lose, sure-thing, risk-free, easy-money, or profit-promising language", "Chasing losses, increasing stakes, irresponsible wagering encouragement, or direct instructions to wager", "Claims that a later winning pick survived after an earlier miss", "Results or leaderboard claims before the trusted contest is finalized", "Invented urgency, contest availability, lock times, or card counts", "Mocking participants, creators, experts, or bots for losing"],
  factualRequirements: ["Use trusted supplied product context for sport, slate, games, available pick options, card size, rank order, contest timing, lock state, grading state, results, surviving legs, first miss, bots, streaks, Perfect 8s, leaderboards, odds, and ROI", "Never invent a pick or market that is not available in the supplied contest", "Distinguish card submitted, locked, grading, final, and archived states", "Only call a card surviving when every preceding ranked pick has actually survived under the contest rules", "Treat status transitions and regrading as updates to the same trusted card record", "Use finalized data for receipts, records, Perfect 8s, streaks, and leaderboard claims", "If trusted card or result data is unavailable, use challenge, education, or invitation content rather than invented activity"],
  affiliationRestrictions: ["Never imply affiliation with a sportsbook, operator, league, team, media company, creator, or expert unless trusted context explicitly establishes it", "Never imply a creator, expert, or AI personally submitted a card unless trusted product context establishes the submitted identity", "Do not claim regulatory approval, guaranteed fairness, or independently verified results without explicit trusted support"],
  aiOperatingInstructions: ["Treat confidence ordering as the defining mechanic", "Treat survival as the emotional engine", "Lead with How deep can you go? when appropriate", "Remember: ordering is the game; survival is the drama", "Use Your picks aren't the challenge. Your confidence is. as supporting strategic territory", "Never reduce Handicap Hero to generic sports picks or picking eight winners", "Make the consequence of rank order easy to understand: the first miss ends the card", "Use Beat the Bots as a major recurring editorial engine only with trusted bot cards and results", "Use Perfect 8, streaks, results, receipts, and reputation only from trusted finalized data", "Never fabricate cards, picks, ranks, surviving legs, results, bots, participation, odds, payouts, ROI, streaks, Perfect 8s, or leaderboard results", "Use responsible language around odds, ROI, wagering, and risk", "Keep consumer participation free-to-play and skill-focused", "Distinguish Handicap Hero from RankEyeQ: RankEyeQ ranks the player field; Handicap Hero ranks conviction and survives the card", "Distinguish Handicap Hero from FantasyTrack: FantasyTrack picks a player to win a position race; Handicap Hero orders confidence across a card", "Distinguish consumer messaging from creator, media, operator, partner, and investor outreach", "Create genuinely different editorial angles from other SNG brands addressing the same sports event"],
};

export const fantasyTrackBrandBrain: BrandBrainFormValue = {
  purpose: "Turn fantasy player performance into live position races. Instead of only asking how many points one player will score, FantasyTrack asks which player will finish first across the entire eligible positional field.",
  corePromise: "Every player. One race. Who finishes first?",
  coreProposition: "The players are the field. The game is the race. FantasyTrack reframes fantasy performance from player-versus-projection into player-versus-player across a full position field, with the live leaderboard becoming the racetrack. For qualified industry audiences, its separate B2B thesis is that participant conviction can allow the field to price itself.",
  audience: "Fantasy football players and NFL fans who understand player performance and enjoy predicting which player will outperform the entire positional field—especially people who follow weekly scoring, live leaderboards, breakouts, long shots, DFS, player props, and the Sunday slate.",
  secondaryAudiences: ["DFS players", "Sports bettors", "Player-prop audiences", "Prediction-market users", "Fantasy analysts", "Sports creators", "Sports prediction enthusiasts", "Data and statistics-oriented sports fans"],
  distributionAudiences: ["Prediction-market operators", "Fantasy operators", "Gaming operators", "Sports betting companies", "Sports-tech companies", "Gaming-industry executives", "Sports-tech investors", "Strategic partners", "Sports business media", "Fantasy and gaming media", "Fantasy creators", "DFS and betting creators", "Sports creators"],
  jobsToBeDone: ["Let me predict which player will outperform the entire positional field and follow that prediction as a live race", "Who finishes RB1 this week?", "Who is my pick to win the QB race?", "Can my player beat the whole field?", "Who is leading right now?", "Is my player still alive?", "Who is making a run?", "Can the long shot hold on?", "Who is moving up the leaderboard?", "Who wins the afternoon?", "Can I identify the breakout before everyone else?", "What does the public think?", "Which players are being backed?", "Turn a full Sunday of scattered player performances into one simple story: who is winning the race?", "For industry audiences: enable participant conviction to establish effective pricing across a broad player field"],
  contentPillars: ["The Position Race", "Player vs Player", "Live Race", "Long Shots / Breakouts", "Public Conviction", "The Field Prices Itself"],
  voice: "Consumer voice is energetic, competitive, sports-native, fast-moving, clear, excited, smart, visual, concise, and race-oriented. It should feel like calling a race, not publishing a spreadsheet. B2B voice is innovative, mechanically credible, commercially aware, confident, curious, and never hype-heavy.",
  voiceTraits: ["Energetic", "Competitive", "Sports-native", "Fast-moving", "Clear", "Excited", "Smart", "Visual", "Concise", "Race-oriented"],
  communicationPatterns: ["Every player at the position becomes one competitive field", "Move from player-versus-projection to player-versus-player", "Invite the audience to pick a runner", "Use race language only when trusted state supports it", "Separate pre-race prediction, live-race movement, and finalized results", "Treat long-shot and public-conviction stories as data-dependent", "Keep consumer storytelling simple and visual", "Reserve the field-prices-itself thesis primarily for industry, partner, and investor contexts"],
  contentModes: [
    { name: "Acquire", goal: "Get fantasy players interested in entering a position race", example: "Every RB. One race. Who finishes first?" },
    { name: "Pick Your Runner", goal: "Drive pre-slate participation around position, field, selection, and conviction" },
    { name: "Pre-Race", goal: "Build anticipation using trusted field, participation, and position storylines" },
    { name: "Live Race", goal: "Turn trusted live fantasy scoring into accurate race commentary" },
    { name: "Results", goal: "Declare the winner and summarize the race using finalized trusted data" },
    { name: "Long Shot / Breakout", goal: "Highlight unexpected leaders or winners when trusted pricing or participation data supports it" },
    { name: "Public Conviction", goal: "Use trusted participation and pool data to explain what users believed" },
    { name: "Industry / B2B", goal: "Explain self-pricing field mechanics and strategic opportunity to qualified industry audiences" },
    { name: "Outreach", goal: "Recruit creators, media, operators, investors, and strategic relationships with audience-specific messaging" },
  ],
  prohibitedContent: ["Fabricated entries, users, selections, pool size, or pool distribution", "Fabricated odds, effective prices, payouts, ROI, favorites, long-shot status, or market movement", "Fabricated fantasy scores, leaderboard positions, lead changes, race results, or historical results", "Fabricated creator participation, partnerships, or product activity", "Unsupported first-ever, exclusivity, guaranteed-liquidity, no-risk, or operator-risk-elimination claims", "Promises of profit, guaranteed outcomes, easy money, or can't-miss wagers", "Chasing-losses or irresponsible financial language", "Manufactured wagering urgency", "Generic fantasy-advice, ranking, start/sit, DFS-lineup, isolated player-prop, or fixed-odds positioning", "Invented exacta, trifecta, box, prop, or future contest mechanics", "Unsupported legal or regulatory conclusions"],
  factualRequirements: ["Use trusted product context for sport, slate, position, eligible field, scoring, contest type, pool structure, lock timing, entries, pricing, scores, leaderboard, results, payouts, and ROI", "Never call a player a long shot without trusted pre-race pricing, participation, odds, or supplied context", "Never describe a lead change, comeback, or live leader without trusted live scoring", "Never manufacture public conviction or market movement", "Distinguish field open, pre-race, locked/start, live race, finish, and finalized result states", "If live or market data is unavailable, use invitation and prediction content instead", "Do not assume every FantasyTrack contest uses identical mechanics"],
  affiliationRestrictions: ["Never imply creator, operator, media, partner, league, or data-provider participation or affiliation without trusted context", "Do not claim that a partner requires FantasyTrack mechanics", "Do not claim exclusivity or regulatory approval without explicit trusted support"],
  aiOperatingInstructions: ["Treat player-versus-field competition as the defining consumer mechanic", "Make the position race easy to understand", "Treat the live leaderboard as a race only when trusted data supports it", "Use energetic, sports-native, race-oriented language", "Recognize long-shot leaders and lead changes as high-value opportunities only when trusted data supports them", "Use public-conviction and market data only when supplied", "Distinguish pre-race, live-race, and final-result states", "Never fabricate entries, odds, pool data, fantasy scores, leaders, payouts, ROI, or results", "Never invent product mechanics", "Distinguish the simple consumer race story from the B2B self-pricing-field story", "Use The field prices itself primarily for industry, partner, investor, and operator contexts", "Avoid generic fantasy-advice positioning", "Avoid reducing FantasyTrack to an isolated player-prop product", "Use responsible language around wagering, pricing, payouts, and risk", "Distinguish consumer messaging from creator, media, operator, partner, and investor outreach", "Create genuinely different editorial angles from RankEyeQ and Handicap Hero", "Remember: the players are the field; the game is the race"],
};

export const eyezOnThePrizeBrandBrain: BrandBrainFormValue = {
  purpose: "Give consumer attention tangible value through a clear, transparent exchange: a participant completes the required sponsor experience, receives a legitimate verified entry, and can see the drawing and resulting winner.",
  corePromise: "Your Attention Is Worth Something.",
  coreProposition: "Eyez on the Prize turns willing consumer attention into transparent participation. The consumer experience stays simple—Watch → Entry → Drawing → Winner—while the separate commercial thesis explains how attention can become a transparent value exchange for brands, sponsors, agencies, and partners.",
  audience: "Consumers and fans willing to give a brand a defined amount of genuine attention when the value exchange is clear, the prize is relevant, and the entry and outcome are transparent.",
  secondaryAudiences: ["Sports and entertainment fans", "Promotion participants", "Prize- and experience-oriented consumers", "Consumers who value clear incentives and transparent outcomes"],
  distributionAudiences: ["Brands", "Advertisers", "Sponsors", "Agencies", "Sports teams and leagues", "Venues", "Media and entertainment companies", "Creators", "Fan-engagement platforms", "Loyalty and engagement companies", "Sports-tech partners", "Marketing and advertising executives"],
  jobsToBeDone: ["Let me exchange a defined amount of my attention for a legitimate opportunity to win something I care about", "Make my attention feel recognized rather than taken for granted", "Show me what I can win and what I need to do", "Confirm that I earned a unique, verified entry", "Tell me when the drawing occurs and how the winner is selected", "Let me see the result and know that someone actually won", "For sponsors: create a reason for consumers to voluntarily provide meaningful, measurable attention", "For sponsors: connect the audience, message, and prize through participation rather than a passive impression"],
  contentPillars: ["Attention Has Value", "Clear Exchange", "Verified Participation", "Transparent Outcome", "Prizes Worth Paying Attention To", "Attention → Participation"],
  voice: "Consumer voice is clear, exciting, confident, modern, slightly playful, premium, transparent, concise, and trustworthy—reward-oriented without sounding cheap. Commercial voice is smart, clear, commercially aware, innovative, measurable, consumer-respectful, confident, and free of ad-tech jargon.",
  voiceTraits: ["Clear", "Exciting", "Confident", "Modern", "Premium", "Transparent", "Concise", "Trustworthy"],
  communicationPatterns: ["Keep the consumer model simple: Watch → Entry → Drawing → Winner", "Lead consumer messaging with Your Attention Is Worth Something", "Explain exactly what the participant does and receives", "Treat attention as something a brand earns rather than captures", "Connect audience, sponsor, message, and prize when trusted campaign context supplies them", "Use Turn attention into participation for appropriate commercial contexts", "Keep consumer and commercial storytelling distinct", "Use transparency around entries, drawings, and winners only from trusted product state"],
  contentModes: [
    { name: "Acquire", goal: "Interest an eligible consumer in a real Eyez campaign by making the prize and value exchange clear" },
    { name: "Explain", goal: "Make Watch → Entry → Drawing → Winner immediately understandable" },
    { name: "Campaign / Prize", goal: "Highlight a real active campaign and prize using trusted campaign data" },
    { name: "Countdown / Scarcity", goal: "Create anticipation using only real supplied deadlines, capacity, remaining entries, or drawing dates" },
    { name: "Completion / Entry", goal: "Confirm successful participation only when trusted user and product state supports it", example: "You watched. You're in." },
    { name: "Drawing", goal: "Build anticipation around an actual scheduled drawing" },
    { name: "Winner / Proof", goal: "Show the real outcome and public proof after a completed drawing" },
    { name: "Sponsor Story", goal: "Explain why a real sponsor, audience, message, and prize fit together" },
    { name: "Industry / B2B", goal: "Explain the attention-value-exchange thesis to commercial and industry audiences" },
    { name: "Outreach", goal: "Recruit sponsors, brands, creators, media, and strategic partners with audience-specific messaging" },
  ],
  prohibitedContent: ["Fabricated sponsors, campaigns, prizes, prize values, videos, partnerships, or testimonials", "Fabricated users, completed views, verified entries, entry counts, remaining entries, campaign capacity, or participation", "Fabricated deadlines, drawing dates, winners, fulfillment, campaign performance, engagement, completion, conversion, or ROI", "Fake urgency, countdowns, scarcity, odds, or chances of winning", "Guaranteed completion, engagement, conversion, winner, prize, outcome, or zero-fraud claims", "Free-money, easy-cash, get-rich, watch-ads-for-cash, lottery, gambling, or betting positioning", "Scammy, sweepstakes-spammy, casino-like, manipulative, cheap, desperate, or deceptive language", "Generic ad-tech jargon or complicated advertising economics in consumer messaging", "Claims that future functionality, sponsors, prizes, campaigns, or integrations are currently live", "Legal conclusions or invented eligibility, entry, drawing, prize, tax, or official-rule terms"],
  factualRequirements: ["Use trusted supplied product, Campaign, Activation, and legal context for sponsors, prizes, content, completion, entry mechanics, capacity, eligibility, timing, drawings, winners, proof, fulfillment, and performance", "Never exaggerate what verified means or claim fraud-proof, tamper-proof, independently audited, or cryptographically guaranteed without explicit trusted support", "Use duration, scarcity, entry confirmation, drawing, winner, and fulfillment language only when current trusted state supports it", "Never fabricate a live campaign to make content interesting; use the brand thesis, explainers, clearly labeled concepts, sponsor outreach, or product education instead", "Marketing copy must not substitute for official rules", "Keep brand thesis distinct from current product capability"],
  affiliationRestrictions: ["Never imply sponsor, brand, creator, team, league, venue, media, or partner involvement unless trusted context explicitly establishes it", "Never imply a prize, campaign, testimonial, or commercial relationship exists without trusted context"],
  aiOperatingInstructions: ["Begin from the belief that consumer attention has value", "Keep consumer mechanics extremely simple: Watch → Entry → Drawing → Winner", "Treat transparency and trust as essential", "Distinguish consumer messaging from sponsor and industry messaging", "Use Your Attention Is Worth Something as the primary consumer posture", "Use attention can become a transparent value exchange primarily for commercial and industry contexts", "Treat attention as something brands earn, not something they are entitled to capture", "Make the prize relevant to the audience only when trusted context supplies one", "Never fabricate sponsors, prizes, campaigns, entries, scarcity, performance, partnerships, testimonials, or winners", "Never manufacture urgency, odds, or chances of winning", "Use campaign and legal context for eligibility and promotional terms", "Never describe future product functionality as live", "Avoid scammy sweepstakes, watch-ads-for-cash, casino, gambling, lottery, and ad-tech-jargon positioning", "Create genuinely different editorial angles from other SNG brands addressing the same event", "Remember the editorial question: What is your attention worth?"],
};

