import Link from "next/link";
import { notFound } from "next/navigation";
import { ConfirmButton } from "@/components/command-center/confirm-button";
import { Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { FormNotice } from "@/components/command-center/form-notice";
import { requireCommandCenterUser } from "@/lib/auth/session";
import { updateCampaignStatus } from "@/lib/command-center/actions";
import { activeCampaignGaps, formatMinor } from "@/lib/growth/campaign-contract";
import { exclusiveEndToInclusive, formatMetricValue } from "@/lib/growth/measurements";
import { canEditGrowth } from "@/lib/growth/permissions";
import { loadTargetProgress } from "@/lib/growth/scorecard";
import { addCampaignReviewAction, createCampaignTargetAction, deleteCampaignTargetAction } from "@/lib/growth/server-actions";
import { formatCalendarDay, formatCentralDate, formatCentralDateTime } from "@/lib/growth/time";
import { prisma } from "@/lib/prisma";

const decisionTone: Record<string, string> = { CONTINUE: "text-[#b8d4c8]", EXPAND: "text-[#87d2ac]", REVISE: "text-[#f0bd65]", STOP: "text-[#ec7f72]" };

export default async function CampaignDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ id }, notice, user] = await Promise.all([params, searchParams, requireCommandCenterUser()]);
  const campaign = await prisma.campaign.findUnique({ where: { id }, include: { program: true, owner: true, brands: true, markets: true, teams: true, activations: { include: { market: true, team: true, brands: true, _count: { select: { relationships: true, opportunities: true } } }, orderBy: [{ priority: "desc" }, { startsAt: "asc" }] }, relationships: { include: { organization: true } }, relationshipLinks: { include: { relationship: { include: { organization: true } } } }, activities: { include: { relationship: { include: { organization: true } }, activation: true }, orderBy: { occurredAt: "desc" } }, attribution: { orderBy: { capturedAt: "desc" } }, reviews: { include: { reviewedBy: true }, orderBy: { reviewedAt: "desc" } }, _count: { select: { targets: true } }, opportunities: { include: { opportunity: { include: { angles: { include: { drafts: true } } } } } } } });
  if (!campaign) notFound();
  const brandIds = campaign.brands.map((brand) => brand.id);
  const [targets, definitions, recentMeasurements] = await Promise.all([
    loadTargetProgress({ campaignId: id }),
    prisma.growthMetricDefinition.findMany({ where: { brandId: { in: brandIds }, status: "ACTIVE" }, include: { brand: { select: { name: true } } }, orderBy: [{ brandId: "asc" }, { key: "asc" }] }),
    prisma.growthMeasurement.findMany({ where: { campaignId: id, status: "REVIEWED", supersededBy: { is: null } }, include: { definition: { select: { label: true, version: true, unit: true } } }, orderBy: { asOfAt: "desc" }, take: 20 }),
  ]);
  const content = campaign.opportunities.flatMap((link) => link.opportunity.angles.flatMap((angle) => angle.drafts));
  const gaps = activeCampaignGaps({ ...campaign, brandIds, targetCount: campaign._count.targets });
  const relationships = new Map([...campaign.relationships.map((relationship) => [relationship.id, relationship] as const), ...campaign.relationshipLinks.map((link) => [link.relationship.id, link.relationship] as const)]);
  const editable = canEditGrowth(user.role);

  return <div><Link href="/command-center/campaigns" className="text-xs text-[#b8d4c8]">← Campaigns</Link>
    <div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-[10px] uppercase tracking-[.15em] text-[#b8d4c8]">{campaign.program?.name || "Unassigned program"} · {campaign.objectiveType.replaceAll("_", " ")} · {campaign.status}</p><h1 className="mt-2 font-display text-3xl text-white">{campaign.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#929795]">{campaign.objective || campaign.description || "Objective not set"}</p></div><div className="flex h-fit flex-wrap gap-2"><Link href={`/command-center/campaigns/${id}/edit`} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white">Edit Campaign</Link><Link href={`/command-center/campaigns/${id}/activations/new`} className="rounded-lg bg-[#b8d4c8] px-3 py-2 text-xs font-semibold text-[#07100c]">Add Activation</Link></div></div>
    <FormNotice saved={notice.saved} error={notice.error} />

    {campaign.status === "ACTIVE" && gaps.length > 0 && <div className="mt-5 rounded-xl border border-[#f0bd65]/30 bg-[#f0bd65]/5 px-4 py-3 text-sm text-[#e2c58f]"><b>Legacy ACTIVE campaign — brief incomplete.</b> It remains ACTIVE (no automatic pause). Missing: {gaps.join(", ")}. These must be completed before material strategy edits or re-activation.</div>}
    {campaign.status !== "ACTIVE" && editable && <div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${gaps.length ? "border-white/10 text-[#8f9391]" : "border-[#87d2ac]/30 text-[#a9dcc1]"}`}>{gaps.length ? <>Not ready to activate. Missing: {gaps.join(", ")}.</> : <>Brief complete — ready to activate.</>}</div>}

    <section className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-xl text-white">What are we trying to make happen?</h2>{editable && <form action={updateCampaignStatus.bind(null, id)} className="flex items-end gap-2"><Select label="Status" name="status" defaultValue={campaign.status}>{["PLANNING", "ACTIVE", "PAUSED", "COMPLETE", "ARCHIVED"].map((status) => <option key={status}>{status}</option>)}</Select><button className="rounded-lg border border-white/10 px-3 py-2.5 text-xs text-white">Update status</button></form>}</div>
      <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["Owner", campaign.owner?.name || campaign.owner?.email], ["Audience", campaign.primaryAudience], ["Offer", campaign.offer], ["Participation action / CTA", campaign.primaryCta], ["Hypothesis", campaign.hypothesis], ["Destination", campaign.destinationUrl || (campaign.executionPlan ? `Non-web plan: ${campaign.executionPlan}` : null)], ["Timing (CT)", `${formatCalendarDay(campaign.startsAt, "Open")} → ${formatCalendarDay(campaign.endsAt, "Open ended")}`], ["Core message", campaign.coreMessage]].map(([label, value]) => <div key={label}><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">{label}</p><p className="mt-2 break-words text-sm text-white">{value || "Not set"}</p></div>)}</div>
      <div className="mt-5 grid gap-5 border-t border-white/7 pt-5 sm:grid-cols-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">Expected time</p><p className="mt-2 text-sm text-white">{campaign.expectedMinutes === null ? "Unknown" : `${campaign.expectedMinutes} min`}</p></div><div><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">Planned spend</p><p className="mt-2 text-sm text-white">{formatMinor(campaign.plannedSpendMinor, campaign.currency)}</p></div><div><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">Actual spend</p><p className="mt-2 text-sm text-white">{formatMinor(campaign.actualSpendMinor, campaign.currency)}</p></div></div>
      <div className="mt-5 border-t border-white/7 pt-5"><p className="text-xs text-[#747976]">Success definition</p><p className="mt-2 text-sm text-white">{campaign.successDefinition || "Not defined yet."}</p><div className="mt-3 flex flex-wrap gap-2">{campaign.kpis.map((kpi) => <span key={kpi} className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8bcba]">{kpi}</span>)}</div></div></section>

    <section className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Targets</h2><p className="mt-1 text-xs text-[#747976]">Actuals use reviewed measurements attributed to this campaign only. Missing data shows UNKNOWN.</p>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[.12em] text-[#747976]"><tr><th className="py-2 pr-3">Metric</th><th className="pr-3">Brand / activation</th><th className="pr-3">Period (CT)</th><th className="pr-3">Baseline</th><th className="pr-3">Target</th><th className="pr-3">Reviewed actual</th><th className="pr-3">As of</th><th /></tr></thead><tbody>{targets.map((target) => <tr key={target.id} className="border-t border-white/7 align-top text-[#d4d7d5]"><td className="py-3 pr-3"><span className="text-white">{target.definition.label}</span><small className="block text-[#747976]">{target.definition.key} v{target.definition.version} · {target.definition.aggregation}</small></td><td className="pr-3">{target.brandName}{target.activationName ? <small className="block text-[#747976]">{target.activationName}</small> : null}</td><td className="pr-3">{formatCentralDate(target.periodStart)} – {formatCentralDate(exclusiveEndToInclusive(target.periodEnd))}</td><td className="pr-3">{formatMetricValue(target.baselineValue, target.definition.unit)}</td><td className="pr-3">{formatMetricValue(target.targetValue, target.definition.unit)}</td><td className={`pr-3 ${target.actual.status === "UNKNOWN" ? "text-[#f0bd65]" : "text-white"}`}>{formatMetricValue(target.actual.value, target.definition.unit)}<small className="block text-[#747976]">{target.actual.basis}{target.actual.pendingReview ? ` · ${target.actual.pendingReview} awaiting review` : ""}</small></td><td className="pr-3">{target.actual.asOfAt ? formatCentralDateTime(target.actual.asOfAt) : "—"}{target.stale && <small className="block text-[#f0bd65]">Stale (&gt;{target.definition.freshnessDays}d)</small>}</td><td>{editable && <form action={deleteCampaignTargetAction.bind(null, target.id)}><ConfirmButton confirmation="Remove this target?" className="text-xs text-[#ec7f72]">Remove</ConfirmButton></form>}</td></tr>)}</tbody></table>{!targets.length && <p className="py-4 text-sm text-[#777b78]">No numeric targets yet. An ACTIVE campaign needs at least one.</p>}</div>
      {editable && (definitions.length ? <details className="mt-4 rounded-xl border border-white/8 p-4"><summary className="cursor-pointer text-xs text-[#b8d4c8]">Add target</summary><form action={createCampaignTargetAction.bind(null, id)} className="mt-4 grid gap-4 sm:grid-cols-3">
        <Select label="Metric definition (ACTIVE)" name="metricDefinitionId" required><option value="">Select…</option>{definitions.map((definition) => <option key={definition.id} value={definition.id}>{definition.brand.name} · {definition.label} (v{definition.version}, {definition.unit})</option>)}</Select>
        <Select label="Activation (optional)" name="activationId"><option value="">Campaign-level</option>{campaign.activations.map((activation) => <option key={activation.id} value={activation.id}>{activation.name}</option>)}</Select>
        <Field label="Target value" name="targetValue" required inputMode="decimal" />
        <Field label="Baseline (blank = unknown)" name="baselineValue" inputMode="decimal" />
        <Field label="Period start (CT)" name="periodStart" type="date" required />
        <Field label="Period end (CT, inclusive)" name="periodEnd" type="date" required />
        <Field label="Due (CT, optional)" name="dueAt" type="date" />
        <div className="sm:col-span-2"><Field label="Measurement plan / notes" name="notes" /></div>
        <div><SubmitButton>Add target</SubmitButton></div>
      </form></details> : <p className="mt-4 text-xs text-[#f0bd65]">No ACTIVE metric definitions for this campaign&apos;s brands. <Link href="/command-center/scorecards" className="underline">Define one on Scorecards</Link>.</p>)}
    </section>

    <section id="decisions" className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Decisions and learning</h2><p className="mt-1 text-xs text-[#747976]">Append-only. Each review records what we learned and what we decided.</p>
      <div className="mt-4 space-y-3">{campaign.reviews.map((review) => <div key={review.id} className="rounded-xl border border-white/7 p-4"><p className="text-xs"><b className={decisionTone[review.decision]}>{review.decision}</b> <span className="text-[#747976]">· {formatCentralDateTime(review.reviewedAt)} · {review.reviewedBy?.name || review.reviewedBy?.email || "Unknown reviewer"}</span></p><p className="mt-2 whitespace-pre-wrap text-sm text-white">{review.learning}</p>{Array.isArray((review.evidence as { links?: string[] } | null)?.links) && ((review.evidence as { links: string[] }).links.length > 0) && <ul className="mt-2 space-y-1 text-xs text-[#8f9391]">{(review.evidence as { links: string[] }).links.map((link) => <li key={link} className="break-all">{link}</li>)}</ul>}</div>)}{!campaign.reviews.length && <p className="text-sm text-[#777b78]">No decision recorded yet.</p>}</div>
      {editable && <details className="mt-4 rounded-xl border border-white/8 p-4"><summary className="cursor-pointer text-xs text-[#b8d4c8]">Record a decision</summary><form action={addCampaignReviewAction.bind(null, id)} className="mt-4 grid gap-4">
        <Select label="Decision" name="decision" required><option value="">Select…</option>{["CONTINUE", "EXPAND", "REVISE", "STOP"].map((decision) => <option key={decision}>{decision}</option>)}</Select>
        <TextArea label="What did we learn?" name="learning" rows={3} required />
        <TextArea label="Evidence links (one per line)" name="evidenceLinks" rows={2} />
        {recentMeasurements.length > 0 && <div><p className="mb-2 text-xs text-[#747976]">Reviewed measurements used as evidence</p><div className="flex flex-wrap gap-2">{recentMeasurements.map((measurement) => <label key={measurement.id} className="flex items-center gap-2 rounded-full border border-white/10 px-3 py-1.5 text-xs text-[#b8bcba]"><input type="checkbox" name="measurementIds" value={measurement.id} />{measurement.definition.label} v{measurement.definition.version}: {formatMetricValue(measurement.value === null ? null : Number(measurement.value), measurement.definition.unit)} ({formatCentralDate(measurement.periodStart)})</label>)}</div></div>}
        <div><SubmitButton>Record decision</SubmitButton></div>
      </form></details>}
    </section>

    <section className="mt-7"><div className="flex items-center justify-between"><h2 className="font-display text-xl text-white">Where and when are we executing?</h2><span className="text-xs text-[#747976]">{campaign.activations.length} activations</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{campaign.activations.map((activation) => <Link key={activation.id} href={`/command-center/campaigns/${id}/activations/${activation.id}`} className="rounded-2xl border border-white/8 bg-[#101214] p-5 hover:border-[#b8d4c8]/30"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.14em] text-[#b8d4c8]">{activation.status}</p><h3 className="mt-2 text-base font-semibold text-white">{activation.name}</h3></div><span className="text-xs text-[#b8d4c8]">{activation.priority}</span></div><p className="mt-3 text-xs text-[#8f9391]">{activation.market?.name || activation.audienceSegment || "Portfolio-wide"}{activation.team ? ` · ${activation.team.name}` : ""}{activation.sport ? ` · ${activation.sport}${activation.week ? ` Week ${activation.week}` : ""}` : ""}</p><p className="mt-3 text-xs text-[#747976]">{activation._count.opportunities} opportunities · {activation._count.relationships} relationships</p></Link>)}{!campaign.activations.length && <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-[#777b78]">No activations yet. Add a market/team/event or audience/sport/week execution.</div>}</div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Opportunities</p><p className="mt-2 text-2xl text-white">{campaign.opportunities.length}</p><Link href={`/command-center/opportunities?campaign=${id}`} className="mt-4 inline-block text-xs text-[#b8d4c8]">Create / view opportunity →</Link></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Content</p><p className="mt-2 text-2xl text-white">{content.length}</p><p className="mt-4 text-xs text-[#747976]">Created through the existing Opportunity workflow</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Relationships / outreach</p><p className="mt-2 text-2xl text-white">{relationships.size} / {campaign.activities.length}</p><Link href={`/command-center/relationships?campaign=${id}`} className="mt-4 inline-block text-xs text-[#b8d4c8]">Open campaign pipeline →</Link></div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">What are we doing?</h2><div className="mt-4 space-y-3">{campaign.opportunities.map((link) => <Link key={link.opportunityId} href={`/command-center/opportunities/${link.opportunityId}/edit`} className="block rounded-xl border border-white/7 p-3 text-sm text-white">{link.opportunity.title}<small className="mt-1 block text-[#747976]">{link.opportunity.status} · {link.opportunity.angles.reduce((sum, angle) => sum + angle.drafts.length, 0)} content items</small></Link>)}{!campaign.opportunities.length && <p className="text-sm text-[#777b78]">No Opportunities or Content yet.</p>}</div></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Outreach activity</h2><div className="mt-4 space-y-3">{campaign.activities.slice(0,6).map((activity) => <Link key={activity.id} href={`/command-center/relationships/${activity.relationshipId}`} className="block text-sm text-white">{activity.relationship.organization.name} · {activity.executionType?.replaceAll("_", " ") || activity.type}{activity.direction ? ` · ${activity.direction.toLowerCase()}` : ""}<small className="block text-[#747976]">{activity.summary}</small></Link>)}{!campaign.activities.length && <p className="text-sm text-[#777b78]">No campaign outreach recorded.</p>}</div></div></section>
    <section className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Is it working?</h2>{campaign.attribution.length ? <><p className="mt-2 text-xs text-[#747976]">Legacy attribution records are shown individually and are not summed: their periods may overlap or be cumulative. Use targets and reviewed measurements for totals.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[.12em] text-[#747976]"><tr><th className="py-2 pr-3">Captured</th><th className="pr-3">Source</th><th className="pr-3">Visits</th><th className="pr-3">Signups</th><th className="pr-3">Conversions</th></tr></thead><tbody>{campaign.attribution.map((item) => <tr key={item.id} className="border-t border-white/7 text-[#d4d7d5]"><td className="py-2 pr-3">{formatCentralDateTime(item.capturedAt)}</td><td className="pr-3">{[item.source, item.medium, item.campaignCode].filter(Boolean).join(" / ") || "—"}</td><td className="pr-3">{item.visits}</td><td className="pr-3">{item.signups}</td><td className="pr-3">{item.conversions}</td></tr>)}</tbody></table></div></> : <p className="mt-4 text-sm text-[#777b78]">No results have been recorded. Metrics will appear only when real attribution or product signals exist.</p>}</section>
  </div>;
}
