import Link from "next/link";
import { notFound } from "next/navigation";
import { Select } from "@/components/command-center/form-fields";
import { updateCampaignStatus } from "@/lib/command-center/actions";
import { prisma } from "@/lib/prisma";

export default async function CampaignDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const campaign = await prisma.campaign.findUnique({ where: { id }, include: { brands: true, markets: true, teams: true, events: true, organizations: true, relationships: true, attribution: true, opportunities: { include: { opportunity: { include: { angles: { include: { drafts: true } } } } } } } });
  if (!campaign) notFound();
  const contentCount = campaign.opportunities.reduce((sum, x) => sum + x.opportunity.angles.reduce((n, angle) => n + angle.drafts.length, 0), 0);
  const visits = campaign.attribution.reduce((sum, x) => sum + x.visits, 0), conversions = campaign.attribution.reduce((sum, x) => sum + x.conversions, 0);
  return <div><Link href="/command-center/campaigns" className="text-xs text-[#b8d4c8]">← Campaigns</Link><div className="mt-5 flex justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.15em] text-[#b8d4c8]">{campaign.status}</p><h1 className="mt-2 font-display text-3xl text-white">{campaign.name}</h1><p className="mt-3 max-w-3xl text-sm text-[#929795]">{campaign.objective || campaign.description}</p></div><div><p className="text-xs text-[#747976]">{campaign.startsAt?.toLocaleDateString() || "No start"} → {campaign.endsAt?.toLocaleDateString() || "Open ended"}</p><form action={updateCampaignStatus.bind(null, campaign.id)} className="mt-3 flex items-end gap-2"><Select label="Status" name="status" defaultValue={campaign.status}>{["PLANNING","ACTIVE","PAUSED","COMPLETE","ARCHIVED"].map((x) => <option key={x}>{x}</option>)}</Select><button className="rounded-lg border border-white/10 px-3 py-2.5 text-xs text-white">Update</button></form></div></div><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Opportunities",campaign.opportunities.length],["Content",contentCount],["Relationships",campaign.relationships.length],["Visits / conversions",`${visits} / ${conversions}`]].map(([label,value]) => <div key={label} className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">{label}</p><p className="mt-3 text-2xl text-white">{value}</p></div>)}</section><section className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Strategy context</h2><p className="mt-4 text-sm text-[#929795]">Brands: {campaign.brands.map((x) => x.name).join(" · ") || "None"}</p><p className="mt-2 text-sm text-[#929795]">Markets: {campaign.markets.map((x) => x.name).join(" · ") || "None"}</p><p className="mt-2 text-sm text-[#929795]">Teams: {campaign.teams.map((x) => x.name).join(" · ") || "None"}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Opportunities</h2><div className="mt-4 space-y-3">{campaign.opportunities.map((x) => <Link key={x.opportunityId} href="/command-center/opportunities" className="block rounded-xl border border-white/7 p-3 text-sm text-white">{x.opportunity.title}</Link>)}{!campaign.opportunities.length && <p className="text-sm text-[#777b78]">No opportunities linked yet.</p>}</div></div></section></div>;
}
