import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function CampaignDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const campaign = await prisma.campaign.findUnique({ where: { id }, include: { program: true, brands: true, markets: true, teams: true, activations: { include: { market: true, team: true, brands: true, _count: { select: { relationships: true, opportunities: true } } }, orderBy: [{ priority: "desc" }, { startsAt: "asc" }] }, relationships: { include: { organization: true } }, activities: { include: { relationship: { include: { organization: true } }, activation: true }, orderBy: { occurredAt: "desc" } }, attribution: true, opportunities: { include: { opportunity: { include: { angles: { include: { drafts: true } } } } } } } });
  if (!campaign) notFound();
  const content = campaign.opportunities.flatMap((link) => link.opportunity.angles.flatMap((angle) => angle.drafts));
  const visits = campaign.attribution.reduce((sum, item) => sum + item.visits, 0), conversions = campaign.attribution.reduce((sum, item) => sum + item.conversions, 0);
  return <div><Link href="/command-center/campaigns" className="text-xs text-[#b8d4c8]">← Campaigns</Link><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-[10px] uppercase tracking-[.15em] text-[#b8d4c8]">{campaign.program?.name || "Unassigned program"} · {campaign.objectiveType.replaceAll("_", " ")}</p><h1 className="mt-2 font-display text-3xl text-white">{campaign.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#929795]">{campaign.objective || campaign.description || "Objective not set"}</p></div><div className="flex h-fit gap-2"><Link href={`/command-center/campaigns/${id}/edit`} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white">Edit Campaign</Link><Link href={`/command-center/campaigns/${id}/activations/new`} className="rounded-lg bg-[#b8d4c8] px-3 py-2 text-xs font-semibold text-[#07100c]">Add Activation</Link></div></div>
    <section className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">What are we trying to make happen?</h2><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["Audience",campaign.primaryAudience],["Core message",campaign.coreMessage],["Primary CTA",campaign.primaryCta],["Timing",`${campaign.startsAt?.toLocaleDateString() || "Open"} → ${campaign.endsAt?.toLocaleDateString() || "Open ended"}`]].map(([label,value]) => <div key={label}><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">{label}</p><p className="mt-2 text-sm text-white">{value || "Not set"}</p></div>)}</div><div className="mt-5 border-t border-white/7 pt-5"><p className="text-xs text-[#747976]">Success definition</p><p className="mt-2 text-sm text-white">{campaign.successDefinition || "Not defined yet."}</p><div className="mt-3 flex flex-wrap gap-2">{campaign.kpis.map((kpi) => <span key={kpi} className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8bcba]">{kpi}</span>)}</div></div></section>
    <section className="mt-7"><div className="flex items-center justify-between"><h2 className="font-display text-xl text-white">Where and when are we executing?</h2><span className="text-xs text-[#747976]">{campaign.activations.length} activations</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{campaign.activations.map((activation) => <Link key={activation.id} href={`/command-center/campaigns/${id}/activations/${activation.id}`} className="rounded-2xl border border-white/8 bg-[#101214] p-5 hover:border-[#b8d4c8]/30"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.14em] text-[#b8d4c8]">{activation.status}</p><h3 className="mt-2 text-base font-semibold text-white">{activation.name}</h3></div><span className="text-xs text-[#b8d4c8]">{activation.priority}</span></div><p className="mt-3 text-xs text-[#8f9391]">{activation.market?.name || activation.audienceSegment || "Portfolio-wide"}{activation.team ? ` · ${activation.team.name}` : ""}{activation.sport ? ` · ${activation.sport}${activation.week ? ` Week ${activation.week}` : ""}` : ""}</p><p className="mt-3 text-xs text-[#747976]">{activation._count.opportunities} opportunities · {activation._count.relationships} relationships</p></Link>)}{!campaign.activations.length && <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-[#777b78]">No activations yet. Add a market/team/event or audience/sport/week execution.</div>}</div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Opportunities</p><p className="mt-2 text-2xl text-white">{campaign.opportunities.length}</p><Link href={`/command-center/opportunities?campaign=${id}`} className="mt-4 inline-block text-xs text-[#b8d4c8]">Create / view opportunity →</Link></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Content</p><p className="mt-2 text-2xl text-white">{content.length}</p><p className="mt-4 text-xs text-[#747976]">Created through the existing Opportunity workflow</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Relationships / outreach</p><p className="mt-2 text-2xl text-white">{campaign.relationships.length} / {campaign.activities.length}</p><Link href="/command-center/relationships" className="mt-4 inline-block text-xs text-[#b8d4c8]">Open shared pipeline →</Link></div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">What are we doing?</h2><div className="mt-4 space-y-3">{campaign.opportunities.map((link) => <Link key={link.opportunityId} href={`/command-center/opportunities/${link.opportunityId}/edit`} className="block rounded-xl border border-white/7 p-3 text-sm text-white">{link.opportunity.title}<small className="mt-1 block text-[#747976]">{link.opportunity.status} · {link.opportunity.angles.reduce((sum, angle) => sum + angle.drafts.length, 0)} content items</small></Link>)}{!campaign.opportunities.length && <p className="text-sm text-[#777b78]">No Opportunities or Content yet.</p>}</div></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Outreach activity</h2><div className="mt-4 space-y-3">{campaign.activities.slice(0,6).map((activity) => <Link key={activity.id} href={`/command-center/relationships/${activity.relationshipId}`} className="block text-sm text-white">{activity.relationship.organization.name} · {activity.executionType?.replaceAll("_", " ") || activity.type}<small className="block text-[#747976]">{activity.summary}</small></Link>)}{!campaign.activities.length && <p className="text-sm text-[#777b78]">No campaign outreach recorded.</p>}</div></div></section>
    <section className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Is it working?</h2>{campaign.attribution.length ? <p className="mt-4 text-sm text-white">{visits} visits · {conversions} conversions</p> : <p className="mt-4 text-sm text-[#777b78]">No results have been recorded. Metrics will appear only when real attribution or product signals exist.</p>}</section>
  </div>;
}
