import Link from "next/link";
import { PageHeader } from "@/components/command-center/page-header";
import { SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { prisma } from "@/lib/prisma";
import { applySportsRosterImport, previewSportsRosterImport } from "@/lib/sports/actions";

const views = ["overview", "players", "defenses", "rosters", "imports", "quality"] as const;
type View = (typeof views)[number];

function Card({ label, value, detail }: { label: string; value: string | number; detail?: string }) {
  return <article className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#6f7471]">{label}</p><p className="mt-2 font-display text-3xl text-white">{value}</p>{detail && <p className="mt-2 text-xs text-[#8f9391]">{detail}</p>}</article>;
}

export default async function SportsPage({ searchParams }: { searchParams: Promise<{ view?: string; run?: string }> }) {
  const params = await searchParams;
  const view: View = views.includes(params.view as View) ? params.view as View : "overview";
  const [season, teams, participantCount, playerCount, defenseCount, rosterCount, openIssues, runs, players, defenses, memberships, selectedRun] = await Promise.all([
    prisma.sportsSeason.findUnique({ where: { league_year: { league: "NFL", year: 2026 } } }),
    prisma.team.count({ where: { league: "NFL", active: true } }),
    prisma.sportsParticipant.count({ where: { active: true } }),
    prisma.player.count({ where: { participant: { active: true } } }),
    prisma.teamDefense.count({ where: { participant: { active: true }, team: { league: "NFL" } } }),
    prisma.seasonRosterMembership.count({ where: { season: { league: "NFL", year: 2026 }, active: true } }),
    prisma.sportsDataQualityIssue.count({ where: { status: "OPEN" } }),
    prisma.sportsIngestionRun.findMany({ take: 10, orderBy: { createdAt: "desc" }, include: { _count: { select: { records: true } } } }),
    prisma.player.findMany({ take: 200, orderBy: { participant: { canonicalName: "asc" } }, include: { participant: { include: { externalIdentities: true, aliases: true, rosterMemberships: { include: { season: true, team: true } } } } } }),
    prisma.teamDefense.findMany({ orderBy: { team: { name: "asc" } }, include: { team: true, participant: { include: { externalIdentities: true } } } }),
    prisma.seasonRosterMembership.findMany({ where: { season: { league: "NFL", year: 2026 } }, orderBy: [{ team: { name: "asc" } }, { participant: { canonicalName: "asc" } }], include: { team: true, participant: true } }),
    params.run ? prisma.sportsIngestionRun.findUnique({ where: { id: params.run }, include: { records: { orderBy: { rowNumber: "asc" } } } }) : null,
  ]);
  const issues = view === "quality" ? await prisma.sportsDataQualityIssue.findMany({ where: { status: "OPEN" }, orderBy: { createdAt: "desc" }, include: { participant: true } }) : [];
  const activePlayerMemberships = memberships.filter((membership) => membership.active && membership.participant.kind === "PLAYER");
  const playerTeamCoverage = new Set(activePlayerMemberships.map((membership) => membership.teamId)).size;
  const examplePayload = JSON.stringify({ league: "NFL", year: 2026, sourceLabel: "Operator supplied roster", sourceReference: "internal roster worksheet", rows: [{ provider: "manual", externalId: "provider-player-id", canonicalName: "Player Name", aliases: [], teamAbbreviation: "MIN", fantasyPosition: "RB", sourcePosition: "RB", status: "ACTIVE", active: true }] }, null, 2);

  return <div><PageHeader title="Sports Data" description="Canonical NFL identity, complete season rosters, provider mappings, and operator-controlled ingestion. Statistics and scoring remain intentionally separate." />
    <nav className="mt-6 flex flex-wrap gap-2">{views.map((item) => <Link key={item} href={`/command-center/sports?view=${item}`} className={`rounded-full border px-3 py-1.5 text-xs capitalize ${view === item ? "border-[#b8d4c8]/50 bg-[#b8d4c8]/10 text-[#d7eee4]" : "border-white/10 text-[#929795]"}`}>{item === "defenses" ? "DEF/DST" : item}</Link>)}</nav>

    {view === "overview" && <><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Active scope" value={season?.label ?? "NFL 2026"} detail="Identity and rosters only"/><Card label="Canonical teams" value={teams} detail="Existing Game-Day teams reused"/><Card label="Players / DEF" value={`${playerCount} / ${defenseCount}`} detail={`${participantCount} active participants`}/><Card label="Active roster memberships" value={rosterCount} detail={`${activePlayerMemberships.length} players + ${defenseCount} DEF/DST`}/><Card label="Player team coverage" value={`${playerTeamCoverage} / 32`} detail={`${activePlayerMemberships.length} active player memberships`}/><Card label="Open quality issues" value={openIssues} detail="Ambiguous and unresolved records"/><Card label="Latest imports" value={runs.length} detail="Preview/apply history retained"/></section><section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Operating boundary</h2><p className="mt-3 max-w-4xl text-sm leading-6 text-[#a4a8a6]">GrowthEvent remains the canonical schedule. This module owns participant identity, external mappings, team defenses, and season roster membership. League rosters arrive through a versioned, operator-controlled RankEyeQ export—not a live database connection. No statistics, fantasy scoring, or external scraping is enabled.</p></section></>}

    {view === "players" && <section className="mt-8 overflow-hidden rounded-2xl border border-white/8 bg-[#101214]"><div className="grid grid-cols-[2fr_1fr_1fr_1.5fr] border-b border-white/8 px-5 py-3 text-[10px] uppercase tracking-wider text-[#6f7471]"><span>Canonical player</span><span>Team</span><span>Position</span><span>External identity</span></div>{players.map(({ participant }) => { const membership = participant.rosterMemberships.find((x) => x.active && x.season.year === 2026 && x.season.league === "NFL") ?? participant.rosterMemberships.find((x) => x.season.year === 2026 && x.season.league === "NFL"); return <div key={participant.id} className="grid grid-cols-[2fr_1fr_1fr_1.5fr] gap-3 border-b border-white/5 px-5 py-4 text-sm last:border-0"><div><p className="text-white">{participant.canonicalName}</p><p className="text-xs text-[#737875]">{participant.aliases.map((x) => x.alias).join(" · ") || "No aliases"}</p></div><span className="text-[#b1b5b3]">{membership?.team.abbreviation ?? "—"}</span><span className="text-[#b1b5b3]">{membership?.fantasyPosition ?? "—"}</span><span className="text-xs text-[#8f9391]">{participant.externalIdentities.map((x) => `${x.provider}:${x.externalId}`).join(" · ") || "Missing"}</span></div>})}{players.length === 0 && <p className="p-6 text-sm text-[#8f9391]">No canonical players imported yet. Preview a trusted roster import first.</p>}</section>}

    {view === "defenses" && <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{defenses.map((defense) => <article key={defense.id} className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="font-medium text-white">{defense.participant.canonicalName}</p><p className="mt-2 text-xs text-[#8f9391]">{defense.team.abbreviation} · canonical Team: {defense.team.name}</p><p className="mt-2 text-[11px] text-[#666b68]">{defense.participant.externalIdentities.map((x) => `${x.provider}:${x.externalId}`).join(" · ")}</p></article>)}</section>}

    {view === "rosters" && <section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">NFL 2026 roster memberships</h2><p className="mt-2 text-sm text-[#8f9391]">Season/team membership is historical; importing a later team does not rewrite the participant identity.</p><div className="mt-5 space-y-2">{memberships.map((membership) => <div key={membership.id} className="grid grid-cols-[2fr_1fr_1fr_1fr] rounded-xl border border-white/7 px-4 py-3 text-sm"><span className="text-white">{membership.participant.canonicalName}</span><span>{membership.team.abbreviation}</span><span>{membership.fantasyPosition}</span><span className="text-[#8f9391]">{membership.status}</span></div>)}</div></section>}

    {view === "imports" && <section className="mt-8 grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><article className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Preview roster import</h2><p className="mt-2 text-sm text-[#8f9391]">JSON is parsed, validated, matched, and retained as an auditable preview. Nothing is committed until Apply is explicitly selected.</p><form action={previewSportsRosterImport} className="mt-5 space-y-4"><TextArea label="NFL 2026 roster JSON" name="rawPayload" rows={18} defaultValue={examplePayload}/><SubmitButton>Preview import</SubmitButton></form></article><article className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Recent runs</h2><div className="mt-4 space-y-3">{runs.map((run) => <Link key={run.id} href={`/command-center/sports?view=imports&run=${run.id}`} className="block rounded-xl border border-white/7 p-4"><div className="flex justify-between gap-3"><span className="text-sm text-white">{run.sourceLabel}</span><span className="text-xs text-[#b8d4c8]">{run.status}</span></div><p className="mt-2 text-xs text-[#777b78]">{run._count.records} rows · +{run.createdCount} / ~{run.updatedCount} / ={run.unchangedCount} · {run.unresolvedCount} unresolved</p></Link>)}</div></article>{selectedRun && <article className="xl:col-span-2 rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl text-white">Run detail · {selectedRun.status}</h2><p className="mt-1 text-xs text-[#777b78]">SHA-256 {selectedRun.checksum} · parser {selectedRun.parserVersion}</p></div>{selectedRun.status === "PREVIEWED" && selectedRun.unresolvedCount === 0 && selectedRun.errorCount === 0 && <form action={applySportsRosterImport}><input type="hidden" name="runId" value={selectedRun.id}/><SubmitButton>Apply approved import</SubmitButton></form>}</div><div className="mt-5 space-y-2">{selectedRun.records.map((record) => <div key={record.id} className="flex justify-between gap-4 rounded-xl border border-white/7 px-4 py-3 text-sm"><span>Row {record.rowNumber} · {record.message ?? "Validated"}</span><span className="text-[#b8d4c8]">{record.status}</span></div>)}</div></article>}</section>}

    {view === "quality" && <section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Open data-quality queue</h2><div className="mt-5 space-y-3">{issues.map((issue) => <article key={issue.id} className="rounded-xl border border-amber-400/15 bg-amber-400/[.03] p-4"><div className="flex justify-between gap-4"><span className="text-sm text-white">{issue.summary}</span><span className="text-xs text-amber-200">{issue.type}</span></div><p className="mt-2 text-xs text-[#8f9391]">{issue.participant?.canonicalName ?? "No canonical participant assigned"}</p></article>)}{issues.length === 0 && <p className="text-sm text-[#8f9391]">No open identity or roster issues.</p>}</div></section>}
  </div>;
}
