import Link from "next/link";
import { PageHeader } from "@/components/command-center/page-header";
import { prisma } from "@/lib/prisma";

export default async function CampaignsPage() {
  const [programs, upcoming, campaigns] = await Promise.all([
    prisma.growthProgram.findMany({ include: { brands: true, campaigns: { include: { activations: true, attribution: true } } }, orderBy: { name: "asc" } }),
    prisma.campaignActivation.findMany({ where: { status: { in: ["READY", "ACTIVE", "PLANNED"] } }, include: { campaign: { include: { program: true } }, market: true, team: true, brands: true, _count: { select: { relationships: true, opportunities: true } } }, orderBy: [{ priority: "desc" }, { startsAt: "asc" }], take: 12 }),
    prisma.campaign.findMany({ where: { status: { in: ["PLANNING", "ACTIVE", "PAUSED"] } }, include: { program: true, brands: true, activations: true, opportunities: true, relationships: true }, orderBy: { updatedAt: "desc" } }),
  ]);
  return <div><PageHeader title="Campaigns" description="Growth programs turn portfolio strategy into campaigns, activations, execution, and measurable results." />
    <div className="mt-7 flex justify-end"><Link href="/command-center/campaigns/new" className="rounded-lg bg-[#b8d4c8] px-4 py-2.5 text-sm font-semibold text-[#07100c]">Create Campaign</Link></div>
    <section className="mt-6 grid gap-5 xl:grid-cols-2">{programs.map((program) => { const active = program.campaigns.filter((campaign) => campaign.status === "ACTIVE"); const activations = program.campaigns.flatMap((campaign) => campaign.activations).filter((activation) => ["READY", "ACTIVE"].includes(activation.status)); return <article key={program.id} className="rounded-2xl border border-white/8 bg-[#101214] p-6"><p className="text-[10px] uppercase tracking-[.18em] text-[#b8d4c8]">Growth Program</p><h2 className="mt-2 font-display text-2xl text-white">{program.name}</h2><p className="mt-2 text-sm leading-6 text-[#929795]">{program.description}</p><p className="mt-4 rounded-lg bg-white/[.03] px-3 py-2 text-xs text-[#b8d4c8]">{program.operatingDescription}</p><div className="mt-5 grid grid-cols-3 gap-3"><div><p className="text-2xl text-white">{active.length}</p><p className="text-xs text-[#747976]">Active campaigns</p></div><div><p className="text-2xl text-white">{activations.length}</p><p className="text-xs text-[#747976]">Ready / active</p></div><div><p className="text-2xl text-white">{new Set(activations.map((item) => item.marketId).filter(Boolean)).size}</p><p className="text-xs text-[#747976]">Active markets</p></div></div><div className="mt-5 flex flex-wrap gap-2">{program.brands.map((brand) => <span key={brand.id} className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8bcba]">{brand.name}</span>)}</div></article>; })}</section>
    <section className="mt-9"><div className="flex items-center justify-between"><h2 className="font-display text-xl text-white">Upcoming Activations</h2><p className="text-xs text-[#747976]">Where and when execution happens</p></div><div className="mt-4 overflow-hidden rounded-2xl border border-white/8"><div className="grid grid-cols-[1.3fr_1fr_.8fr_.6fr] gap-3 bg-[#0d0f10] px-5 py-3 text-[10px] uppercase tracking-[.12em] text-[#747976]"><span>Activation</span><span>Context</span><span>Brands / relationships</span><span>Priority</span></div>{upcoming.map((activation) => <Link key={activation.id} href={`/command-center/campaigns/${activation.campaignId}/activations/${activation.id}`} className={`grid grid-cols-[1.3fr_1fr_.8fr_.6fr] gap-3 border-t border-white/7 px-5 py-4 text-sm hover:bg-white/[.02] ${activation.key?.includes("minnesota-vikings") ? "bg-[#b8d4c8]/5" : "bg-[#101214]"}`}><span><b className="text-white">{activation.name}</b><small className="mt-1 block text-[#747976]">{activation.campaign.name}</small></span><span className="text-[#a5aaa7]">{activation.market?.name || activation.audienceSegment || "Portfolio-wide"}{activation.team ? ` · ${activation.team.name}` : ""}</span><span className="text-[#8f9391]">{activation.brands.map((brand) => brand.shortName || brand.name).join(" · ") || "Campaign brands"}<small className="mt-1 block">{activation._count.relationships} relationships</small></span><span className="text-[#b8d4c8]">{activation.priority}<small className="mt-1 block text-[#747976]">{activation.status}</small></span></Link>)}{!upcoming.length && <p className="bg-[#101214] p-8 text-center text-sm text-[#777b78]">No upcoming activations yet.</p>}</div></section>
    <section className="mt-9"><h2 className="font-display text-xl text-white">Active Campaigns</h2><div className="mt-4 grid gap-4 xl:grid-cols-2">{campaigns.map((campaign) => <Link href={`/command-center/campaigns/${campaign.id}`} key={campaign.id} className="rounded-2xl border border-white/8 bg-[#101214] p-6 hover:border-[#b8d4c8]/30"><div className="flex justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.14em] text-[#b8d4c8]">{campaign.program?.name || "Unassigned program"}</p><h3 className="mt-2 font-display text-xl text-white">{campaign.name}</h3></div><span className="text-xs text-[#8f9391]">{campaign.status}</span></div><p className="mt-3 text-sm text-[#929795]">{campaign.objective || campaign.description || "Objective not set"}</p><p className="mt-5 text-xs text-[#747976]">{campaign.brands.map((brand) => brand.name).join(" · ") || "No brands"} · {campaign.activations.length} activations · {campaign.opportunities.length} opportunities · {campaign.relationships.length} relationships</p></Link>)}</div></section>
  </div>;
}
