import Link from "next/link";
import { notFound } from "next/navigation";
import { Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { updateBrandProfile, upsertSocialAccount } from "@/lib/command-center/actions";
import { prisma } from "@/lib/prisma";

export default async function BrandDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const brand = await prisma.brand.findUnique({ where: { id }, include: { socialAccounts: true, teams: true, campaigns: true } });
  if (!brand) notFound();
  const terminology = brand.terminology && typeof brand.terminology === "object" && !Array.isArray(brand.terminology) && "notes" in brand.terminology ? (brand.terminology.notes as string[]).join("\n") : "";
  return <div><Link href="/command-center/brands" className="text-xs text-[#b8d4c8]">← Brand Brain</Link><div className="mt-5 flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#747976]">{brand.kind}</p><h1 className="mt-2 font-display text-3xl text-white">{brand.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#929795]">{brand.coreProposition || brand.description}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8d4c8]">{brand.active ? "Active" : "Inactive"}</span></div>
    <section className="mt-8 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Audience</p><p className="mt-3 text-sm leading-6 text-white">{brand.audience}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Voice</p><p className="mt-3 text-sm leading-6 text-white">{brand.voice}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Posting philosophy</p><p className="mt-3 text-sm leading-6 text-white">{brand.defaultCadenceNotes}</p></div></section>
    <section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex justify-between"><div><h2 className="font-display text-lg text-white">Social channels</h2><p className="mt-1 text-xs text-[#747976]">Channel context only. Publishing remains manual and disconnected.</p></div></div><div className="mt-5 flex flex-wrap gap-2">{brand.socialAccounts.map((account) => <span key={account.id} className="rounded-full border border-white/10 px-3 py-2 text-xs text-white">{account.platform} {account.handle || ""} · {account.connectionStatus.replaceAll("_", " ")}</span>)}{!brand.socialAccounts.length && <p className="text-sm text-[#777b78]">No channels configured.</p>}</div><details className="mt-5"><summary className="cursor-pointer text-xs text-[#b8d4c8]">+ Add or update channel</summary><form action={upsertSocialAccount.bind(null, brand.id)} className="mt-4 grid gap-4 sm:grid-cols-3"><Select label="Platform" name="platform">{["X","INSTAGRAM","FACEBOOK","LINKEDIN","TIKTOK","YOUTUBE","THREADS","OTHER"].map((x) => <option key={x}>{x}</option>)}</Select><Field label="Handle" name="handle" /><Field label="Profile URL" name="profileUrl" type="url" /><SubmitButton>Save channel</SubmitButton></form></details></section>
    <details className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><summary className="cursor-pointer font-display text-lg text-white">Edit strategic profile</summary><form action={updateBrandProfile.bind(null, brand.id)} className="mt-6 space-y-4"><div className="grid gap-4 lg:grid-cols-2"><Field label="Short name" name="shortName" defaultValue={brand.shortName || ""} /><TextArea label="Description" name="description" defaultValue={brand.description} rows={3} required /><TextArea label="Purpose / positioning" name="purpose" defaultValue={brand.purpose || ""} rows={3} /><TextArea label="Core proposition" name="coreProposition" defaultValue={brand.coreProposition || ""} rows={3} /><TextArea label="Target audience" name="audience" defaultValue={brand.audience} rows={3} required /><TextArea label="Brand voice" name="voice" defaultValue={brand.voice} rows={3} required /><TextArea label="Brand terminology (one note per line)" name="terminology" defaultValue={terminology} rows={4} /><TextArea label="Content pillars" name="contentPillars" defaultValue={(brand.contentPillars.length ? brand.contentPillars : brand.objectives).join("\n")} rows={4} /><TextArea label="Objectives" name="objectives" defaultValue={brand.objectives.join("\n")} rows={4} /><TextArea label="Preferred content types" name="preferredContent" defaultValue={brand.preferredContent.join("\n")} rows={4} /><TextArea label="Messaging / claims to avoid" name="prohibitedContent" defaultValue={brand.prohibitedContent.join("\n")} rows={4} /><TextArea label="Primary CTAs" name="primaryCtas" defaultValue={brand.primaryCtas.join("\n")} rows={3} /><TextArea label="Relevant URLs" name="relevantUrls" defaultValue={brand.relevantUrls.join("\n")} rows={3} /><TextArea label="CTA rules" name="callToActionRules" defaultValue={brand.callToActionRules} rows={3} required /></div><Field label="Default cadence / posting philosophy" name="defaultCadenceNotes" defaultValue={brand.defaultCadenceNotes} required /><label className="flex items-center gap-2 text-sm text-[#b8bcba]"><input type="checkbox" name="active" defaultChecked={brand.active} /> Active brand</label><SubmitButton>Save profile</SubmitButton></form></details>
  </div>;
}
