import Link from "next/link";
import { notFound } from "next/navigation";
import { Field, Select, SubmitButton } from "@/components/command-center/form-fields";
import { upsertSocialAccount } from "@/lib/command-center/actions";
import { contentModesFromValue, hasConfiguredBrandBrain } from "@/lib/command-center/brand-brain";
import { prisma } from "@/lib/prisma";

function List({ items, empty = "Not configured" }: { items: string[]; empty?: string }) {
  return items.length ? <ul className="mt-3 space-y-2 text-sm leading-6 text-[#d4d7d5]">{items.map((item) => <li key={item} className="flex gap-2"><span className="text-[#b8d4c8]">•</span><span>{item}</span></li>)}</ul> : <p className="mt-3 text-sm text-[#777b78]">{empty}</p>;
}

export default async function BrandDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const brand = await prisma.brand.findUnique({ where: { id }, include: { socialAccounts: true, teams: true, campaigns: true, activations: { include: { campaign: true }, orderBy: { createdAt: "desc" } } } });
  if (!brand) notFound();
  const configured = hasConfiguredBrandBrain(brand);
  const modes = contentModesFromValue(brand.contentModes);
  return <div>
    <Link href="/command-center/brands" className="text-xs text-[#b8d4c8]">← Brand Brain</Link>
    <div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#747976]">{brand.kind} · {configured ? `Brand Brain v${brand.brandBrainVersion}` : "Brand Brain not configured"}</p><h1 className="mt-2 font-display text-3xl text-white">{brand.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#929795]">{configured ? brand.corePromise : brand.coreProposition || brand.description}</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8d4c8]">{brand.active ? "Active" : "Inactive"}</span><Link href={`/command-center/brands/${id}/brain/edit`} className="rounded-lg bg-[#b8d4c8] px-3 py-2 text-xs font-semibold text-[#07100c]">{configured ? "Edit Brand Brain" : "Configure Brand Brain"}</Link></div></div>
    {!configured ? <section className="mt-8 rounded-2xl border border-dashed border-[#b8d4c8]/25 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Brand Brain not yet configured</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#929795]">The existing trusted Brand profile remains available below. Persistent AI-ready strategy has not been intentionally defined for this Brand.</p></section> : <>
      <section className="mt-8 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs uppercase tracking-[.12em] text-[#747976]">Purpose</p><p className="mt-3 text-sm leading-6 text-white">{brand.purpose}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs uppercase tracking-[.12em] text-[#747976]">Core promise</p><p className="mt-3 text-sm leading-6 text-white">{brand.corePromise}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs uppercase tracking-[.12em] text-[#747976]">Positioning</p><p className="mt-3 text-sm leading-6 text-white">{brand.coreProposition}</p></div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Audience</h2><p className="mt-4 text-xs uppercase tracking-[.12em] text-[#747976]">Primary</p><p className="mt-2 text-sm leading-6 text-white">{brand.audience}</p><p className="mt-5 text-xs uppercase tracking-[.12em] text-[#747976]">Secondary</p><List items={brand.secondaryAudiences} /><p className="mt-5 text-xs uppercase tracking-[.12em] text-[#747976]">Distribution / relationships</p><List items={brand.distributionAudiences} /></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Jobs to be done</h2><List items={brand.jobsToBeDone} /></div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Messaging pillars</h2><div className="mt-4 flex flex-wrap gap-2">{brand.contentPillars.map((pillar) => <span key={pillar} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-[#d4d7d5]">{pillar}</span>)}</div></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Voice</h2><p className="mt-3 text-sm leading-6 text-white">{brand.voice}</p><div className="mt-4 flex flex-wrap gap-2">{brand.voiceTraits.map((trait) => <span key={trait} className="rounded-full border border-[#b8d4c8]/20 px-3 py-1.5 text-xs text-[#b8d4c8]">{trait}</span>)}</div><p className="mt-5 text-xs uppercase tracking-[.12em] text-[#747976]">Preferred patterns</p><List items={brand.communicationPatterns} /></div></section>
      <section className="mt-5 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Content modes</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{modes.map((mode) => <div key={mode.name} className="rounded-xl border border-white/7 p-4"><p className="text-sm font-semibold text-white">{mode.name}</p><p className="mt-2 text-xs leading-5 text-[#a2a6a3]">{mode.goal}</p>{mode.example && <p className="mt-3 text-xs italic text-[#b8d4c8]">“{mode.example}”</p>}</div>)}</div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Guardrails</h2><p className="mt-4 text-xs uppercase tracking-[.12em] text-[#747976]">Never</p><List items={brand.prohibitedContent} /><p className="mt-5 text-xs uppercase tracking-[.12em] text-[#747976]">Factual / data requirements</p><List items={brand.factualRequirements} /><p className="mt-5 text-xs uppercase tracking-[.12em] text-[#747976]">Affiliation restrictions</p><List items={brand.affiliationRestrictions} /></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Future AI operating instructions</h2><p className="mt-2 text-xs leading-5 text-[#747976]">Stored strategy only. No model or generation service is connected.</p><List items={brand.aiOperatingInstructions} /></div></section>
    </>}
    {!configured && <section className="mt-5 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Existing audience</p><p className="mt-3 text-sm leading-6 text-white">{brand.audience}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Existing voice</p><p className="mt-3 text-sm leading-6 text-white">{brand.voice}</p></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Existing posting philosophy</p><p className="mt-3 text-sm leading-6 text-white">{brand.defaultCadenceNotes}</p></div></section>}
    <section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Campaign and activation context</h2><p className="mt-1 text-xs text-[#747976]">Operational context remains separate from persistent Brand strategy.</p><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><p className="text-xs uppercase tracking-[.12em] text-[#747976]">Campaigns</p><List items={brand.campaigns.map((campaign) => campaign.name)} empty="No campaigns linked" /></div><div><p className="text-xs uppercase tracking-[.12em] text-[#747976]">Activations</p><List items={brand.activations.map((activation) => `${activation.campaign.name} — ${activation.name}`)} empty="No activations linked" /></div></div></section>
    <section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Social channels</h2><p className="mt-1 text-xs text-[#747976]">Channel context only. Publishing remains manual and disconnected.</p><div className="mt-5 flex flex-wrap gap-2">{brand.socialAccounts.map((account) => <span key={account.id} className="rounded-full border border-white/10 px-3 py-2 text-xs text-white">{account.platform} {account.handle || ""} · {account.connectionStatus.replaceAll("_", " ")}</span>)}{!brand.socialAccounts.length && <p className="text-sm text-[#777b78]">No channels configured.</p>}</div><details className="mt-5"><summary className="cursor-pointer text-xs text-[#b8d4c8]">+ Add or update channel</summary><form action={upsertSocialAccount.bind(null, brand.id)} className="mt-4 grid gap-4 sm:grid-cols-3"><Select label="Platform" name="platform">{["X","INSTAGRAM","FACEBOOK","LINKEDIN","TIKTOK","YOUTUBE","THREADS","OTHER"].map((item) => <option key={item}>{item}</option>)}</Select><Field label="Handle" name="handle" /><Field label="Profile URL" name="profileUrl" type="url" /><SubmitButton>Save channel</SubmitButton></form></details></section>
  </div>;
}
