import { describe,it,expect } from "vitest";
import { canonicalFixture,addNonparticipant } from "./canonical-fixtures.test-helper";
import { buildCanonicalArtifact,verifyCanonicalArtifact,validateCanonicalRun } from "./export";
import { canonicalExportJson,exportChecksum } from "./export-serialization";

const accept=(f:ReturnType<typeof canonicalFixture>)=>({id:"artifact1",seriesKey:"series",revision:1,supersedesId:null,acceptedById:"owner",acceptedAt:"2026-09-30T00:00:00.000Z",reason:"Reviewed fixture",manifestChecksum:exportChecksum(f.manifest)});
describe("immutable canonical weekly artifact",()=>{
  it("contains all fields beyond UI limits and verifies its digest",()=>{const f=canonicalFixture(125);const built=buildCanonicalArtifact(f.run,f.observation,f.manifest,accept(f));expect(canonicalExportJson(verifyCanonicalArtifact(built.bytes))).toBe(built.bytes);expect(built.artifact.payload.resultSets.find(s=>s.positionCode==="WR")!.fieldSize).toBe(125);});
  it("is deterministic with code-unit sorted keys, rejects unsafe values",()=>{expect(canonicalExportJson({b:2,a:1})).toBe(canonicalExportJson({a:1,b:2}));for(const v of [undefined,NaN,Infinity,0.2,Number.MAX_SAFE_INTEGER+1,new Date()])expect(()=>canonicalExportJson({value:v})).toThrow();});
  it("preserves ranked legitimate zero and competition ties",()=>{const f=canonicalFixture(3);const a=buildCanonicalArtifact(f.run,f.observation,f.manifest,accept(f)).artifact;const set=a.payload.resultSets.find(s=>s.positionCode==="WR")!;expect(set.entries.map(e=>e.pointsHundredths)).toEqual([0,0,0]);expect(set.entries.map(e=>e.competitionRank)).toEqual([1,1,1]);expect(set.entries[0].tieGroupSize).toBe(3);});
  it("exports legitimate negative scores with positional rank",()=>{const f=canonicalFixture(1,true);const a=verifyCanonicalArtifact(buildCanonicalArtifact(f.run,f.observation,f.manifest,accept(f)).bytes);expect(a.payload.resultSets.find(s=>s.positionCode==="QB")!.entries[0].pointsHundredths).toBe(-200);});
  it("rejects byte tampering and field truncation",()=>{const f=canonicalFixture();const a=buildCanonicalArtifact(f.run,f.observation,f.manifest,accept(f));expect(()=>verifyCanonicalArtifact(a.bytes.replace('"revision":1','"revision":2'))).toThrow(/checksum/);f.run.weeklyResultSets[0].entries=[];expect(()=>validateCanonicalRun(f.run,f.observation,f.manifest)).toThrow();});
  it("requires frozen reviewed lineage on historical SHADOW runs",()=>{const f=canonicalFixture();f.run.summary=null;expect(()=>validateCanonicalRun(f.run,f.observation,f.manifest)).toThrow(/frozen/);});
  it("cannot publish PREVIEW as accepted SHADOW",()=>{const f=canonicalFixture();f.run.mode="PREVIEW";expect(()=>validateCanonicalRun(f.run,f.observation,f.manifest)).toThrow(/SHADOW/);});
  it("detects corrupt result, source revision, and input checksums",()=>{for(const kind of ["result","input","source"]){const f=canonicalFixture();if(kind==="result")f.run.derivedPerformances[0].pointsHundredths++;if(kind==="input")f.run.inputSnapshots[0].inputChecksum="a".repeat(64);if(kind==="source")f.run.inputSnapshots[0].sourceRevisionFingerprint="a".repeat(64);expect(()=>validateCanonicalRun(f.run,f.observation,f.manifest)).toThrow();}});
  it("retains immutable old bytes when a new revision is generated",()=>{const f=canonicalFixture();const old=buildCanonicalArtifact(f.run,f.observation,f.manifest,accept(f));const revised=buildCanonicalArtifact(f.run,f.observation,f.manifest,{...accept(f),id:"artifact2",revision:2,supersedesId:"artifact1"});expect(revised.artifact.supersedesArtifactId).toBe("artifact1");expect(revised.checksum).not.toBe(old.checksum);expect(verifyCanonicalArtifact(old.bytes).revision).toBe(1);});
  it("serializes affirmative nonparticipants as null/unranked",()=>{const f=canonicalFixture();addNonparticipant(f.manifest,f.observation);expect(f.manifest.participants.at(-1)!.state).toBe("VERIFIED_NON_PARTICIPANT");/* Full calculation must be refreshed for the new manifest checksum. */expect(()=>buildCanonicalArtifact(f.run,f.observation,f.manifest,accept(f))).toThrow(/recalculate/);});
});
