import Link from "next/link";
import { Field, Select } from "@/components/command-center/form-fields";
import { PageHeader } from "@/components/command-center/page-header";
import { scheduleDraft, updateDraftStatus } from "@/lib/command-center/actions";
import { prisma } from "@/lib/prisma";

const statuses = ["DRAFT", "NEEDS_REVIEW", "REVISION_REQUESTED", "APPROVED", "READY", "PUBLISHED", "REJECTED", "ARCHIVED"];
export default async function QueuePage({ searchParams }: { searchParams: Promise<{ status?: string; brand?: string }> }) {
  const filters = await searchParams;
  const [drafts, brands] = await Promise.all([
    prisma.contentDraft.findMany({ where: { status: statuses.includes(filters.status || "") ? filters.status as never : undefined, brandAngle: filters.brand ? { brandId: filters.brand } : undefined }, include: { brandAngle: { include: { brand: { include: { socialAccounts: true } }, opportunity: { include: { markets: true, teams: true, campaigns: { include: { campaign: true } } } } } }, socialAccount: true, approvals: { include: { reviewer: true }, orderBy: { createdAt: "desc" } }, publication: true }, orderBy: { updatedAt: "desc" } }),
    prisma.brand.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
  ]);
  return <div><PageHeader title="Content Queue" description="Draft, review, approve, and schedule—human approval remains the gate before public distribution." />
    <form className="mt-7 flex flex-wrap gap-3"><Select label="Status" name="status" defaultValue={filters.status || ""}><option value="">All statuses</option>{statuses.map((x) => <option key={x}>{x.replaceAll("_", " ")}</option>)}</Select><Select label="Brand" name="brand" defaultValue={filters.brand || ""}><option value="">All brands</option>{brands.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><button className="self-end rounded-lg border border-white/10 px-4 py-2.5 text-sm text-white">Filter</button></form>
    <section className="mt-6 space-y-4">{drafts.length ? drafts.map((draft) => <article key={draft.id} className="rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-[10px] uppercase tracking-[.15em] text-[#b8d4c8]">{draft.brandAngle.brand.name} · {draft.status.replaceAll("_", " ")}</p><h2 className="mt-2 font-display text-xl text-white">{draft.brandAngle.hook}</h2><Link href="/command-center/opportunities" className="mt-1 block text-xs text-[#747976]">From: {draft.brandAngle.opportunity.title}</Link></div>{draft.scheduledFor && <span className="text-xs text-[#b8d4c8]">{draft.scheduledFor.toLocaleString()}</span>}</div><div className="mt-5 whitespace-pre-wrap rounded-xl border border-white/7 bg-[#080a0b] p-5 text-sm leading-6 text-[#d4d7d5]">{draft.body}</div>{draft.callToAction && <p className="mt-3 text-xs text-[#8f9391]">CTA: {draft.callToAction}</p>}<p className="mt-3 text-xs text-[#747976]">Angle: {draft.brandAngle.rationale}</p>
      <div className="mt-5 flex flex-wrap gap-2">{draft.status === "DRAFT" && <form action={updateDraftStatus.bind(null, draft.id)}><input type="hidden" name="status" value="NEEDS_REVIEW" /><button className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white">Send to review</button></form>}{["NEEDS_REVIEW","REVISION_REQUESTED"].includes(draft.status) && <><form action={updateDraftStatus.bind(null, draft.id)}><input type="hidden" name="status" value="APPROVED" /><button className="rounded-lg bg-[#b8d4c8] px-3 py-2 text-xs font-semibold text-[#07100c]">Approve</button></form><form action={updateDraftStatus.bind(null, draft.id)}><input type="hidden" name="status" value="REVISION_REQUESTED" /><button className="rounded-lg border border-[#f0bd65]/30 px-3 py-2 text-xs text-[#f0bd65]">Request revision</button></form><form action={updateDraftStatus.bind(null, draft.id)}><input type="hidden" name="status" value="REJECTED" /><button className="rounded-lg border border-[#ec7f72]/30 px-3 py-2 text-xs text-[#ec7f72]">Reject</button></form></>}{draft.status === "APPROVED" && draft.brandAngle.brand.socialAccounts?.length !== 0 && <details className="w-full rounded-xl border border-white/8 p-4"><summary className="cursor-pointer text-xs text-[#b8d4c8]">Schedule approved content</summary><form action={scheduleDraft.bind(null, draft.id)} className="mt-4 grid gap-4 sm:grid-cols-2"><Select label="Channel" name="socialAccountId" required>{brands.find((b) => b.id === draft.brandAngle.brand.id)?.name && <option value="">Select configured account…</option>}{draft.brandAngle.brand.socialAccounts?.map((account) => <option key={account.id} value={account.id}>{account.platform} {account.handle || ""}</option>)}</Select><Field label="Publish time" name="scheduledFor" type="datetime-local" required /><button className="rounded-lg bg-[#b8d4c8] px-4 py-2 text-xs font-semibold text-[#07100c]">Schedule</button></form></details>}{draft.status === "APPROVED" && !draft.brandAngle.brand.socialAccounts?.length && <p className="w-full text-xs text-[#f0bd65]">Add a social account to this brand before scheduling. No platform publishing is enabled.</p>}</div></article>) : <div className="rounded-2xl border border-dashed border-white/10 p-12 text-center"><p className="text-sm text-white">Nothing in this queue view</p><p className="mt-2 text-xs text-[#777b78]">Create content from an Opportunity to carry its context into a new draft.</p><Link href="/command-center/opportunities" className="mt-4 inline-block text-xs text-[#b8d4c8]">Open Opportunity Feed →</Link></div>}</section>
  </div>;
}
