import { Field, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { PageHeader } from "@/components/command-center/page-header";
import { updateBrandProfile } from "@/lib/command-center/actions";
import { prisma } from "@/lib/prisma";

export default async function BrandsPage() {
  const brands = await prisma.brand.findMany({ orderBy: [{ kind: "asc" }, { name: "asc" }] });
  return <div><PageHeader title="Brands" description="Editable strategic guardrails used before AI recommends an angle or drafts content." /><section className="mt-8 space-y-5">{brands.map((brand) => <form key={brand.id} action={updateBrandProfile.bind(null, brand.id)} className="rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex justify-between gap-4"><h2 className="font-display text-xl text-white">{brand.name}</h2><span className="text-[10px] uppercase tracking-[.14em] text-[#7d817f]">{brand.kind}</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><TextArea label="Description" name="description" defaultValue={brand.description} rows={3} required /><TextArea label="Target audience" name="audience" defaultValue={brand.audience} rows={3} required /><TextArea label="Brand voice" name="voice" defaultValue={brand.voice} rows={3} required /><TextArea label="CTA rules" name="callToActionRules" defaultValue={brand.callToActionRules} rows={3} required /><TextArea label="Preferred content (one per line)" name="preferredContent" defaultValue={brand.preferredContent.join("\n")} rows={4} /><TextArea label="Prohibited messaging (one per line)" name="prohibitedContent" defaultValue={brand.prohibitedContent.join("\n")} rows={4} /><TextArea label="Primary CTAs (one per line)" name="primaryCtas" defaultValue={brand.primaryCtas.join("\n")} rows={3} /><TextArea label="Relevant URLs (one per line)" name="relevantUrls" defaultValue={brand.relevantUrls.join("\n")} rows={3} /></div><div className="mt-4"><Field label="Default cadence" name="defaultCadenceNotes" defaultValue={brand.defaultCadenceNotes} required /></div><div className="mt-5"><SubmitButton>Save profile</SubmitButton></div></form>)}</section></div>;
}
