import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function ActivationDetailPage({ params }: { params: Promise<{ id: string; activationId: string }> }) {
  const { id, activationId } = await params;
  const activation = await prisma.campaignActivation.findFirst({ where: { id: activationId, campaignId: id }, include: { campaign: { include: { program: true } }, market: true, team: true, event: true, brands: true, relationships: { include: { organization: true, relevantBrands: true } }, opportunities: { include: { angles: { include: { drafts: true } } } }, activities: { include: { relationship: { include: { organization: true } } }, orderBy: { occurredAt: "desc" } } } });
  if (!activation) notFound();
  const contentCount = activation.opportunities.reduce((sum, opportunity) => sum + opportunity.angles.reduce((count, angle) => count + angle.drafts.length, 0), 0);
  return <div><Link href={`/command-center/campaigns/${id}`} className="text-xs text-[#b8d4c8]">← {activation.campaign.name}</Link><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-[10px] uppercase tracking-[.15em] text-[#b8d4c8]">{activation.status} · {activation.priority} priority</p><h1 className="mt-2 font-display text-3xl text-white">{activation.name}</h1><p className="mt-2 text-sm text-[#8f9391]">{activation.campaign.program?.name} · {activation.campaign.name}</p></div><div className="flex h-fit gap-2"><Link href={`/command-center/campaigns/${id}/activations/${activationId}/edit`} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white">Edit Activation</Link><Link href={`/command-center/opportunities?campaign=${id}&activation=${activationId}`} className="rounded-lg bg-[#b8d4c8] px-3 py-2 text-xs font-semibold text-[#07100c]">Create Opportunity</Link></div></div>
    <section className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Market / audience",activation.market?.name || activation.audienceSegment],["Team / venue",activation.team?.name || activation.venueName],["Sport / timing",[activation.sport,activation.season,activation.week ? `Week ${activation.week}` : null,activation.slateLabel].filter(Boolean).join(" · ")],["Event",activation.event?.name || activation.startsAt?.toLocaleString()]].map(([label,value]) => <div key={label} className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">{label}</p><p className="mt-3 text-sm text-white">{value || "Not set"}</p></div>)}</section>
    <section className="mt-6 rounded-2xl border border-white/8 bg-[#101214] p-6"><p className="text-xs text-[#747976]">Activation objective</p><p className="mt-2 text-sm text-white">{activation.objective || "Not set"}</p><p className="mt-5 text-xs text-[#747976]">Core message</p><p className="mt-2 text-lg text-white">{activation.coreMessage || "Not set"}</p><p className="mt-5 text-xs text-[#747976]">CTA</p><p className="mt-2 text-sm text-[#b8d4c8]">{activation.callToAction || "Not set"}</p><div className="mt-5 flex flex-wrap gap-2">{activation.brands.map((brand) => <span key={brand.id} className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8bcba]">{brand.name}</span>)}</div></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><h2 className="font-display text-lg text-white">Opportunities</h2><p className="mt-3 text-2xl text-white">{activation.opportunities.length}</p>{activation.opportunities.map((item) => <Link key={item.id} href={`/command-center/opportunities/${item.id}/edit`} className="mt-3 block text-xs text-[#b8d4c8]">{item.title}</Link>)}</div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><h2 className="font-display text-lg text-white">Content</h2><p className="mt-3 text-2xl text-white">{contentCount}</p><Link href="/command-center/queue" className="mt-3 block text-xs text-[#b8d4c8]">Open Content Queue →</Link></div><div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><h2 className="font-display text-lg text-white">Relationship targets</h2>{activation.relationships.map((relationship) => <Link key={relationship.id} href={`/command-center/relationships/${relationship.id}`} className="mt-3 block text-xs text-white">{relationship.organization.name}<small className="block text-[#747976]">{relationship.relevantBrands.map((brand) => brand.name).join(" · ")}</small></Link>)}{!activation.relationships.length && <p className="mt-3 text-sm text-[#777b78]">No shared SNG relationships linked yet.</p>}</div></section>
    <section className="mt-6 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Execution activity</h2>{activation.activities.map((activity) => <p key={activity.id} className="mt-3 text-sm text-white">{activity.occurredAt.toLocaleDateString()} · {activity.executionType?.replaceAll("_", " ") || activity.type} · {activity.relationship.organization.name} — {activity.summary}</p>)}{!activation.activities.length && <p className="mt-3 text-sm text-[#777b78]">No outreach or execution activity recorded.</p>}</section>
  </div>;
}
