import Link from "next/link";
import { notFound } from "next/navigation";
import { SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { updateBrandBrain } from "@/lib/command-center/actions";
import { contentModesToText } from "@/lib/command-center/brand-brain";
import { prisma } from "@/lib/prisma";

export default async function EditBrandBrainPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const brand = await prisma.brand.findUnique({ where: { id } });
  if (!brand) notFound();
  return <div><Link href={`/command-center/brands/${id}`} className="text-xs text-[#b8d4c8]">← {brand.name}</Link><div className="mt-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#747976]">Persistent strategic intelligence</p><h1 className="mt-2 font-display text-3xl text-white">Edit {brand.name} Brand Brain</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#929795]">One item per line for structured lists. Content modes use: Name | Goal | Optional example.</p></div>
    <form action={updateBrandBrain.bind(null, brand.id)} className="mt-8 space-y-5">
      <section className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Identity</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><TextArea label="Brand purpose" name="purpose" defaultValue={brand.purpose || ""} rows={4} required /><TextArea label="Core promise" name="corePromise" defaultValue={brand.corePromise || ""} rows={4} required /></div><div className="mt-4"><TextArea label="Positioning / differentiation" name="coreProposition" defaultValue={brand.coreProposition || ""} rows={5} required /></div></section>
      <section className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Audience and jobs</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><TextArea label="Primary audience" name="audience" defaultValue={brand.audience} rows={5} required /><TextArea label="Secondary audiences (one per line)" name="secondaryAudiences" defaultValue={brand.secondaryAudiences.join("\n")} rows={5} /><TextArea label="Distribution / relationship audiences" name="distributionAudiences" defaultValue={brand.distributionAudiences.join("\n")} rows={7} /><TextArea label="Jobs / questions to be done" name="jobsToBeDone" defaultValue={brand.jobsToBeDone.join("\n")} rows={7} /></div></section>
      <section className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Messaging and voice</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><TextArea label="Messaging pillars" name="contentPillars" defaultValue={brand.contentPillars.join("\n")} rows={6} required /><TextArea label="Communication style" name="voice" defaultValue={brand.voice} rows={6} required /><TextArea label="Voice traits" name="voiceTraits" defaultValue={brand.voiceTraits.join("\n")} rows={7} /><TextArea label="Preferred communication patterns" name="communicationPatterns" defaultValue={brand.communicationPatterns.join("\n")} rows={7} /></div></section>
      <section className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Content modes</h2><div className="mt-5"><TextArea label="Name | Goal | Optional example (one mode per line)" name="contentModes" defaultValue={contentModesToText(brand.contentModes)} rows={10} required /></div></section>
      <section className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Guardrails</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><TextArea label="Prohibited claims / behavior" name="prohibitedContent" defaultValue={brand.prohibitedContent.join("\n")} rows={9} /><TextArea label="Factual / data requirements" name="factualRequirements" defaultValue={brand.factualRequirements.join("\n")} rows={9} /><TextArea label="Affiliation restrictions" name="affiliationRestrictions" defaultValue={brand.affiliationRestrictions.join("\n")} rows={6} /><div className="space-y-4"><TextArea label="Primary CTAs" name="primaryCtas" defaultValue={brand.primaryCtas.join("\n")} rows={4} /><TextArea label="CTA rules" name="callToActionRules" defaultValue={brand.callToActionRules} rows={5} /></div></div></section>
      <section className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Future AI operating instructions</h2><p className="mt-1 text-xs text-[#747976]">Structured strategic instructions only. No AI provider or generator is connected.</p><div className="mt-5"><TextArea label="One instruction per line" name="aiOperatingInstructions" defaultValue={brand.aiOperatingInstructions.join("\n")} rows={14} required /></div></section>
      <div className="flex items-center gap-3"><SubmitButton>Save Brand Brain</SubmitButton><Link href={`/command-center/brands/${id}`} className="text-sm text-[#929795]">Cancel</Link></div>
    </form>
  </div>;
}
