import Link from "next/link";
import { PageHeader } from "@/components/command-center/page-header";
import { listSocialProviderAdapters } from "@/lib/social-accounts/providers/registry";
import { prisma } from "@/lib/prisma";

export default async function IntegrationsPage() {
  const [applications, authorizations, accounts] = await Promise.all([
    prisma.socialPlatformApplication.findMany({ include: { _count: { select: { authorizations: true } } }, orderBy: [{ platform: "asc" }, { environment: "asc" }] }),
    prisma.socialAuthorization.findMany({ include: { platformApplication: true, authorizedBy: { select: { name: true, email: true } }, _count: { select: { accounts: true } } }, orderBy: { updatedAt: "desc" }, take: 50 }),
    prisma.socialAccount.findMany({ include: { brand: true, _count: { select: { authorizationLinks: true, capabilitySnapshots: true } } }, orderBy: [{ platform: "asc" }, { brand: { name: "asc" } }] }),
  ]);
  const adapters = listSocialProviderAdapters();
  return <div><Link href="/command-center/settings" className="text-xs text-[#b8d4c8]">← Settings</Link><div className="mt-4"><PageHeader title="Integrations" description="Canonical social identity and connection inventory. Live authorization is disabled until a credential vault and provider applications are separately approved." /></div>
    <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{adapters.map((adapter) => <article key={adapter.platform} className="rounded-2xl border border-white/8 bg-[#101214] p-5"><div className="flex justify-between gap-3"><h2 className="font-display text-lg text-white">{adapter.platform}</h2><span className="rounded-full border border-amber-300/20 px-2 py-1 text-[10px] text-amber-200">AUTH DISABLED</span></div><p className="mt-3 text-xs text-[#8f9391]">{adapter.adapterVersion}</p><p className="mt-2 text-xs text-[#747976]">{adapter.supportsMultipleAccountsPerAuthorization ? "One authorization may expose multiple identities" : "One identity per authorization"}</p></article>)}</section>
    <section className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl text-white">Platform applications</h2><span className="text-xs text-[#747976]">{applications.length}</span></div><div className="mt-5 space-y-3">{applications.map((app) => <div key={app.id} className="rounded-xl border border-white/7 p-4"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm text-white">{app.key}</span><span className="text-xs text-[#b8d4c8]">{app.environment} · {app.status}</span></div><p className="mt-2 text-xs text-[#747976]">{app.platform} · {app._count.authorizations} authorizations · credential values never displayed</p></div>)}{!applications.length && <p className="text-sm text-[#777b78]">No provider applications registered. This is the expected foundation state.</p>}</div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><article className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Authorizations</h2><div className="mt-5 space-y-3">{authorizations.map((authorization) => <div key={authorization.id} className="rounded-xl border border-white/7 p-4"><p className="text-sm text-white">{authorization.platformApplication.platform} · {authorization.status}</p><p className="mt-2 text-xs text-[#747976]">{authorization._count.accounts} accounts · owner {authorization.authorizedBy?.name || authorization.authorizedBy?.email || "system/unassigned"}</p></div>)}{!authorizations.length && <p className="text-sm text-[#777b78]">No OAuth authorizations. No real accounts are connected.</p>}</div></article>
      <article className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">Account inventory</h2><div className="mt-5 space-y-3">{accounts.map((account) => <Link href={`/command-center/brands/${account.brandId}`} key={account.id} className="block rounded-xl border border-white/7 p-4"><div className="flex justify-between gap-3"><span className="text-sm text-white">{account.displayName || account.handle || `${account.platform} identity`}</span><span className="text-xs text-[#b8d4c8]">{account.brand.name}</span></div><p className="mt-2 text-xs text-[#747976]">{account.platform} · {account.accountType} · {account.lifecycleStatus} · {account.externalAccountId ? "identity verified" : "identity unverified"}</p><p className="mt-1 text-[11px] text-[#666b68]">{account._count.authorizationLinks} authorization links · {account._count.capabilitySnapshots} capability snapshots</p></Link>)}{!accounts.length && <p className="text-sm text-[#777b78]">No known social accounts have been inventoried.</p>}</div></article></section>
  </div>;
}

