import Link from "next/link";
import { CheckboxGroup, Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { FormNotice } from "@/components/command-center/form-notice";
import { PageHeader } from "@/components/command-center/page-header";
import { createOrganization, createRelationship } from "@/lib/command-center/actions";
import { requireCommandCenterUser } from "@/lib/auth/session";
import { canEditGrowth } from "@/lib/growth/permissions";
import { loadRelationshipViews } from "@/lib/growth/relationship-read";
import { isRelationshipViewKey, relationshipOperatingRules, relationshipViewLabels, type RelationshipViewKey } from "@/lib/growth/relationships";
import { formatCentralDate } from "@/lib/growth/time";
import { prisma } from "@/lib/prisma";

const stages = ["PROSPECT", "CONTACTED", "CONVERSATION", "OPPORTUNITY", "PARTNER", "CLOSED", "NOT_PURSUING"];
const types = ["MEDIA", "TEAM", "CREATOR_NETWORK", "CREATOR", "PODCAST", "VENUE", "PARTNER", "AGENCY", "INVESTOR", "OTHER"];
const viewKeys: RelationshipViewKey[] = ["due", "overdue", "noNextAction", "stalled", "recentResponses"];

export default async function RelationshipsPage({ searchParams }: { searchParams: Promise<{ view?: string; campaign?: string; owner?: string; brand?: string; saved?: string; error?: string }> }) {
  const [filters, user] = await Promise.all([searchParams, requireCommandCenterUser()]);
  const editable = canEditGrowth(user.role);
  const where = {
    ...(filters.campaign ? { OR: [{ campaignId: filters.campaign }, { campaignLinks: { some: { campaignId: filters.campaign } } }] } : {}),
    ...(filters.owner ? { ownerId: filters.owner } : {}),
    ...(filters.brand ? { relevantBrands: { some: { id: filters.brand } } } : {}),
  };
  const [{ rows: relationships, views }, organizations, markets, brands, campaigns, users] = await Promise.all([loadRelationshipViews(where), prisma.organization.findMany({ orderBy: { name: "asc" } }), prisma.market.findMany({ orderBy: { name: "asc" } }), prisma.brand.findMany({ orderBy: { name: "asc" } }), prisma.campaign.findMany({ where: { status: { in: ["PLANNING", "ACTIVE", "PAUSED"] } }, orderBy: { name: "asc" }, select: { id: true, name: true } }), prisma.user.findMany({ select: { id: true, name: true, email: true }, orderBy: { email: "asc" } })]);
  const view = isRelationshipViewKey(filters.view) ? filters.view : null;
  const query = (next: Record<string, string | undefined>) => {
    const params = new URLSearchParams(Object.entries({ campaign: filters.campaign, owner: filters.owner, brand: filters.brand, view: filters.view, ...next }).filter((entry): entry is [string, string] => Boolean(entry[1])));
    const value = params.toString();
    return value ? `/command-center/relationships?${value}` : "/command-center/relationships";
  };
  const tab = "rounded-full border px-3 py-1.5 text-xs";

  return <div><PageHeader title="Relationship Pipeline" description="A lightweight operating pipeline for SNG’s media, creator, team, venue, and partner relationships." />
    <FormNotice saved={filters.saved} error={filters.error} />
    <form className="mt-7 flex flex-wrap gap-3"><input type="hidden" name="view" value={filters.view ?? ""} /><Select label="Campaign" name="campaign" defaultValue={filters.campaign ?? ""}><option value="">All campaigns</option>{campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</Select><Select label="Owner" name="owner" defaultValue={filters.owner ?? ""}><option value="">Any owner</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name || user.email}</option>)}</Select><Select label="Brand" name="brand" defaultValue={filters.brand ?? ""}><option value="">All brands</option>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</Select><button className="self-end rounded-lg border border-white/10 px-4 py-2.5 text-sm text-white">Filter</button></form>
    <nav className="mt-5 flex flex-wrap gap-2" aria-label="Relationship views"><Link href={query({ view: undefined })} className={`${tab} ${!view ? "border-[#b8d4c8]/50 text-[#b8d4c8]" : "border-white/10 text-[#8f9391]"}`}>Pipeline</Link>{viewKeys.map((key) => <Link key={key} href={query({ view: key })} className={`${tab} ${view === key ? "border-[#b8d4c8]/50 text-[#b8d4c8]" : "border-white/10 text-[#8f9391]"}`}>{relationshipViewLabels[key]} <span className="text-[#666]">{views[key].length}</span></Link>)}</nav>
    <p className="mt-2 text-[11px] text-[#666]">Operating rules, not facts about prospect interest: due = follow-up within {relationshipOperatingRules.dueWithinDays} days (CT); stalled = no activity for {relationshipOperatingRules.stalledAfterDays} days; recent responses = inbound in the last {relationshipOperatingRules.recentResponseDays} days. Legacy activities have unknown direction.</p>

    {view ? <section className="mt-6 overflow-x-auto rounded-2xl border border-white/8 bg-[#101214]"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[.12em] text-[#747976]"><tr><th className="px-4 py-3">Organization</th><th className="pr-3">Stage</th><th className="pr-3">Owner</th><th className="pr-3">Next action</th><th className="pr-3">Due (CT)</th><th className="pr-3">Last activity</th><th className="pr-3">Last inbound</th></tr></thead><tbody>{views[view].map((item) => <tr key={item.id} className="border-t border-white/7 text-[#d4d7d5]"><td className="px-4 py-3"><Link href={`/command-center/relationships/${item.id}`} className="text-white hover:text-[#b8d4c8]">{item.organization.name}</Link><small className="block text-[#747976]">{item.contact?.name || item.name}</small></td><td className="pr-3">{item.stage.replaceAll("_", " ")}</td><td className="pr-3">{item.owner?.name || item.owner?.email || "Unassigned"}</td><td className="pr-3">{item.nextAction || <span className="text-[#f0bd65]">None</span>}</td><td className="pr-3">{formatCentralDate(item.nextFollowUpAt)}</td><td className="pr-3">{formatCentralDate(item.lastActivityAt)}</td><td className="pr-3">{formatCentralDate(item.lastInboundAt)}</td></tr>)}</tbody></table>{!views[view].length && <p className="p-6 text-sm text-[#777b78]">Nothing in this view.</p>}</section>
    : <section className="mt-6 grid gap-4 xl:grid-cols-5">{stages.slice(0,5).map((stage) => <div key={stage} className="rounded-2xl border border-white/8 bg-[#0d0f10] p-4"><div className="flex justify-between"><h2 className="text-xs font-semibold uppercase tracking-[.12em] text-[#b8d4c8]">{stage}</h2><span className="text-xs text-[#666]">{relationships.filter((x) => x.stage === stage).length}</span></div><div className="mt-4 space-y-3">{relationships.filter((x) => x.stage === stage).map((item) => <Link href={`/command-center/relationships/${item.id}`} key={item.id} className="block rounded-xl border border-white/8 bg-[#101214] p-4 hover:border-[#b8d4c8]/30"><p className="text-sm font-medium text-white">{item.organization.name}</p><p className="mt-1 text-xs text-[#8f9391]">{item.contact?.name || item.name}</p><p className={`mt-2 text-xs ${item.nextAction ? "text-[#d4d7d5]" : "text-[#f0bd65]"}`}>{item.nextAction || "No next action"}</p><p className="mt-2 text-[11px] text-[#747976]">{item.organization.market?.name || "No market"} · Due {formatCentralDate(item.nextFollowUpAt)}</p></Link>)}{!relationships.some((x) => x.stage === stage) && <p className="py-6 text-center text-xs text-[#555]">Empty</p>}</div></div>)}</section>}
    {!view && !!relationships.filter((x) => ["CLOSED","NOT_PURSUING"].includes(x.stage)).length && <details className="mt-5 rounded-2xl border border-white/8 p-5"><summary className="cursor-pointer text-sm text-[#8f9391]">Closed / not pursuing</summary><div className="mt-4 space-y-2">{relationships.filter((x) => ["CLOSED","NOT_PURSUING"].includes(x.stage)).map((x) => <Link key={x.id} href={`/command-center/relationships/${x.id}`} className="block text-sm text-white">{x.organization.name} · {x.stage.replaceAll("_", " ")}{x.outcome ? ` — ${x.outcome}` : ""}</Link>)}</div></details>}
    {editable && <details className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><summary className="cursor-pointer font-display text-lg text-white">+ Add organization or relationship</summary><section className="mt-6 grid gap-6 xl:grid-cols-2"><form action={createOrganization} className="space-y-4 rounded-xl border border-white/8 p-5"><h2 className="font-display text-lg text-white">Organization</h2><Field label="Name" name="name" required /><Select label="Type" name="type">{types.map((type) => <option key={type}>{type}</option>)}</Select><Select label="Market" name="marketId"><option value="">None</option>{markets.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><Field label="Website" name="websiteUrl" type="url" /><TextArea label="Notes" name="notes" /><CheckboxGroup name="brandIds" items={brands} /><SubmitButton>Add organization</SubmitButton></form><form action={createRelationship} className="space-y-4 rounded-xl border border-white/8 p-5"><h2 className="font-display text-lg text-white">Relationship</h2><Field label="Relationship name" name="name" required /><Select label="Organization" name="organizationId" required><option value="">Choose…</option>{organizations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><div className="grid gap-4 sm:grid-cols-2"><Field label="Contact name" name="contactName" /><Field label="Role / title" name="contactTitle" /></div><Field label="Next follow-up" name="nextFollowUpAt" type="date" /><TextArea label="Summary" name="summary" /><CheckboxGroup name="brandIds" items={brands} /><SubmitButton>Add relationship</SubmitButton></form></section></details>}
  </div>;
}
