import Link from "next/link";
import { CheckboxGroup, Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { PageHeader } from "@/components/command-center/page-header";
import { createOrganization, createRelationship } from "@/lib/command-center/actions";
import { prisma } from "@/lib/prisma";

const stages = ["PROSPECT", "CONTACTED", "CONVERSATION", "OPPORTUNITY", "PARTNER", "CLOSED", "NOT_PURSUING"];
const types = ["MEDIA", "TEAM", "CREATOR_NETWORK", "CREATOR", "PODCAST", "VENUE", "PARTNER", "AGENCY", "INVESTOR", "OTHER"];
export default async function RelationshipsPage() {
  const [relationships, organizations, markets, brands] = await Promise.all([prisma.relationship.findMany({ include: { organization: { include: { market: true } }, contact: true, owner: true, relevantBrands: true }, orderBy: { updatedAt: "desc" } }), prisma.organization.findMany({ orderBy: { name: "asc" } }), prisma.market.findMany({ orderBy: { name: "asc" } }), prisma.brand.findMany({ orderBy: { name: "asc" } })]);
  return <div><PageHeader title="Relationship Pipeline" description="A lightweight operating pipeline for SNG’s media, creator, team, venue, and partner relationships." />
    <section className="mt-8 grid gap-4 xl:grid-cols-5">{stages.slice(0,5).map((stage) => <div key={stage} className="rounded-2xl border border-white/8 bg-[#0d0f10] p-4"><div className="flex justify-between"><h2 className="text-xs font-semibold uppercase tracking-[.12em] text-[#b8d4c8]">{stage}</h2><span className="text-xs text-[#666]">{relationships.filter((x) => x.stage === stage).length}</span></div><div className="mt-4 space-y-3">{relationships.filter((x) => x.stage === stage).map((item) => <Link href={`/command-center/relationships/${item.id}`} key={item.id} className="block rounded-xl border border-white/8 bg-[#101214] p-4 hover:border-[#b8d4c8]/30"><p className="text-sm font-medium text-white">{item.organization.name}</p><p className="mt-1 text-xs text-[#8f9391]">{item.contact?.name || item.name}</p><p className="mt-3 text-[11px] text-[#747976]">{item.organization.market?.name || "No market"} · Next {item.nextFollowUpAt?.toLocaleDateString() || "unscheduled"}</p></Link>)}{!relationships.some((x) => x.stage === stage) && <p className="py-6 text-center text-xs text-[#555]">Empty</p>}</div></div>)}</section>
    {!!relationships.filter((x) => ["CLOSED","NOT_PURSUING"].includes(x.stage)).length && <details className="mt-5 rounded-2xl border border-white/8 p-5"><summary className="cursor-pointer text-sm text-[#8f9391]">Closed / not pursuing</summary><div className="mt-4 space-y-2">{relationships.filter((x) => ["CLOSED","NOT_PURSUING"].includes(x.stage)).map((x) => <Link key={x.id} href={`/command-center/relationships/${x.id}`} className="block text-sm text-white">{x.organization.name} · {x.stage.replaceAll("_", " ")}</Link>)}</div></details>}
    <details className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><summary className="cursor-pointer font-display text-lg text-white">+ Add organization or relationship</summary><section className="mt-6 grid gap-6 xl:grid-cols-2"><form action={createOrganization} className="space-y-4 rounded-xl border border-white/8 p-5"><h2 className="font-display text-lg text-white">Organization</h2><Field label="Name" name="name" required /><Select label="Type" name="type">{types.map((type) => <option key={type}>{type}</option>)}</Select><Select label="Market" name="marketId"><option value="">None</option>{markets.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><Field label="Website" name="websiteUrl" type="url" /><TextArea label="Notes" name="notes" /><CheckboxGroup name="brandIds" items={brands} /><SubmitButton>Add organization</SubmitButton></form><form action={createRelationship} className="space-y-4 rounded-xl border border-white/8 p-5"><h2 className="font-display text-lg text-white">Relationship</h2><Field label="Relationship name" name="name" required /><Select label="Organization" name="organizationId" required><option value="">Choose…</option>{organizations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><div className="grid gap-4 sm:grid-cols-2"><Field label="Contact name" name="contactName" /><Field label="Role / title" name="contactTitle" /></div><Field label="Next follow-up" name="nextFollowUpAt" type="date" /><TextArea label="Summary" name="summary" /><CheckboxGroup name="brandIds" items={brands} /><SubmitButton>Add relationship</SubmitButton></form></section></details>
  </div>;
}
