import Link from "next/link";
import { CheckboxGroup, Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { ConfirmButton } from "@/components/command-center/confirm-button";
import { PageHeader } from "@/components/command-center/page-header";
import { createOpportunity, deleteOpportunity, updateOpportunityStatus } from "@/lib/command-center/actions";
import { prisma } from "@/lib/prisma";

export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<{ status?: string; brand?: string; campaign?: string; activation?: string }> }) {
  const filters = await searchParams;
  const status = ["NEW", "REVIEWED", "DEVELOPING", "QUEUED", "COMPLETE", "NO_POST", "DISMISSED"].includes(filters.status || "") ? filters.status : undefined;
  const [items, markets, teams, campaigns, brands, activation] = await Promise.all([
    prisma.opportunity.findMany({ where: { status: status as never, angles: filters.brand ? { some: { brandId: filters.brand } } : undefined, campaigns: filters.campaign ? { some: { campaignId: filters.campaign } } : undefined }, include: { activation: true, markets: true, teams: true, campaigns: { include: { campaign: true } }, angles: { include: { brand: true, drafts: { select: { id: true } } } } }, orderBy: [{ urgency: "desc" }, { createdAt: "desc" }], take: 75 }),
    prisma.market.findMany({ orderBy: { name: "asc" } }), prisma.team.findMany({ orderBy: { name: "asc" } }), prisma.campaign.findMany({ orderBy: { name: "asc" } }), prisma.brand.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    filters.activation ? prisma.campaignActivation.findUnique({ where: { id: filters.activation }, include: { campaign: true } }) : null,
  ]);
  return <div><PageHeader title="Opportunity Feed" description="Prioritized signals across SNG—understand what matters, decide what to do, then act." />
    <div className="mt-7 flex flex-wrap items-center justify-between gap-3"><form className="flex flex-wrap gap-2"><Select label="Status" name="status" defaultValue={filters.status || ""}><option value="">All active states</option>{["NEW","REVIEWED","DEVELOPING","QUEUED","COMPLETE","NO_POST","DISMISSED"].map((x) => <option key={x}>{x}</option>)}</Select><Select label="Brand" name="brand" defaultValue={filters.brand || ""}><option value="">All brands</option>{brands.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><button className="self-end rounded-lg border border-white/10 px-4 py-2.5 text-sm text-white">Filter</button></form></div>
    <section className="mt-6 space-y-4">{items.length ? items.map((item) => { const contentCount = item.angles.reduce((sum, angle) => sum + angle.drafts.length, 0); return <article key={item.id} className="rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap gap-2"><span className="text-[10px] uppercase tracking-[.15em] text-[#7f8381]">{item.sourceLabel || "Manual"}</span><span className="text-[10px] uppercase tracking-[.15em] text-[#b8d4c8]">{item.status}</span>{item.activation && <span className="text-[10px] uppercase tracking-[.15em] text-[#f0bd65]">{item.activation.name}</span>}</div><h2 className="mt-2 font-display text-xl text-white">{item.title}</h2></div><span className="h-fit rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8d4c8]">Priority {item.urgency}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><p className="text-[10px] uppercase tracking-[.14em] text-[#707472]">What is happening</p><p className="mt-2 text-sm leading-6 text-[#9ba09d]">{item.summary}</p></div><div><p className="text-[10px] uppercase tracking-[.14em] text-[#707472]">Why it matters</p><p className="mt-2 text-sm leading-6 text-[#9ba09d]">{item.whyItMatters || "Not yet assessed."}</p></div></div>{item.actionRecommendation && <div className="mt-4 rounded-xl bg-[#b8d4c8]/7 p-4 text-sm text-[#c7d9d1]"><b>Recommended action: </b>{item.actionRecommendation}</div>}<p className="mt-4 text-xs text-[#747976]">{[...item.angles.map((x) => x.brand.name), ...item.markets.map((x) => x.name), ...item.teams.map((x) => x.name), ...item.campaigns.map((x) => x.campaign.name)].join(" · ") || "Portfolio-wide"} · {contentCount} content item{contentCount === 1 ? "" : "s"}</p><div className="mt-5 flex flex-wrap gap-2"><Link href={`/command-center/opportunities/${item.id}/content`} className="rounded-lg bg-[#b8d4c8] px-4 py-2 text-xs font-semibold text-[#07100c]">Create content</Link><Link href={`/command-center/opportunities/${item.id}/edit`} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white">Edit</Link>{item.status !== "DISMISSED" && <form action={updateOpportunityStatus.bind(null, item.id)}><input type="hidden" name="status" value="DISMISSED" /><button className="rounded-lg border border-white/10 px-3 py-2 text-xs text-[#b8bcba]">Dismiss</button></form>}{contentCount === 0 && <form action={deleteOpportunity.bind(null, item.id)}><ConfirmButton confirmation={`Delete “${item.title}”? This cannot be undone.`} className="rounded-lg border border-[#ec7f72]/30 px-3 py-2 text-xs text-[#ec7f72]">Delete</ConfirmButton></form>}</div></article>; }) : <div className="rounded-2xl border border-dashed border-white/10 p-12 text-center text-sm text-[#8f9391]">No opportunities match these filters.</div>}</section>
    <details open={Boolean(filters.campaign || filters.activation)} className="mt-8 rounded-2xl border border-white/8 bg-[#101214] p-6"><summary className="cursor-pointer font-display text-lg text-white">+ Add opportunity</summary>{(filters.campaign || activation) && <p className="mt-3 text-xs text-[#b8d4c8]">Context: {activation ? `${activation.campaign.name} → ${activation.name}` : campaigns.find((item) => item.id === filters.campaign)?.name}</p>}<form action={createOpportunity} className="mt-6 space-y-4"><input type="hidden" name="activationId" value={activation?.id || ""} /><Field label="Title" name="title" required /><TextArea label="What is happening?" name="summary" rows={3} required /><TextArea label="Why does it matter?" name="whyItMatters" rows={2} /><TextArea label="What should SNG do?" name="actionRecommendation" rows={2} /><div className="grid gap-4 sm:grid-cols-3"><Field label="Source" name="sourceLabel" /><Field label="Priority (0–100)" name="urgency" type="number" min="0" max="100" defaultValue="50" /><Field label="Recommended by" name="recommendedAt" type="datetime-local" /></div><p className="text-xs text-[#747976]">Markets</p><CheckboxGroup name="marketIds" items={markets} selectedIds={activation?.marketId ? [activation.marketId] : []} /><p className="text-xs text-[#747976]">Teams</p><CheckboxGroup name="teamIds" items={teams} selectedIds={activation?.teamId ? [activation.teamId] : []} /><p className="text-xs text-[#747976]">Campaigns</p><CheckboxGroup name="campaignIds" items={campaigns} selectedIds={filters.campaign ? [filters.campaign] : activation ? [activation.campaignId] : []} /><SubmitButton>Add opportunity</SubmitButton></form></details>
  </div>;
}
