import Link from "next/link";
import { Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { FormNotice } from "@/components/command-center/form-notice";
import { requireCommandCenterUser } from "@/lib/auth/session";
import { exclusiveEndToInclusive, formatMetricValue, funnelStages, metricAggregations, metricUnits } from "@/lib/growth/measurements";
import { canEditGrowth } from "@/lib/growth/permissions";
import { loadTargetProgress } from "@/lib/growth/scorecard";
import { createMetricDefinitionAction, createMetricDefinitionVersionAction, recordMeasurementAction, reviewMeasurementAction, setMetricDefinitionStatusAction } from "@/lib/growth/server-actions";
import { formatCentralDate, formatCentralDateTime, toCentralDateInputValue, toCentralInputValue } from "@/lib/growth/time";
import { prisma } from "@/lib/prisma";

const definitionTone: Record<string, string> = { ACTIVE: "text-[#87d2ac]", DRAFT: "text-[#f0bd65]", RETIRED: "text-[#747976]" };
const measurementTone: Record<string, string> = { REVIEWED: "text-[#87d2ac]", REPORTED: "text-[#f0bd65]", UNKNOWN: "text-[#a6a9ff]" };
const num = (value: { toString(): string } | null) => (value === null ? null : Number(value.toString()));

function DefinitionFields({ defaults }: { defaults?: { key: string; label: string; funnelStage: string; unit: string; aggregation: string; definition: string; numeratorDefinition: string | null; denominatorDefinition: string | null; cohortBasis: string | null; freshnessDays: number | null } }) {
  return <>
    {defaults ? <input type="hidden" name="key" value={defaults.key} /> : <Field label="Key (stable, e.g. signups)" name="key" required pattern="[a-z0-9_\-]+" />}
    <Field label="Label" name="label" required defaultValue={defaults?.label} />
    <Select label="Funnel stage" name="funnelStage" defaultValue={defaults?.funnelStage ?? "SIGNUP"}>{funnelStages.map((item) => <option key={item}>{item}</option>)}</Select>
    <Select label="Unit" name="unit" defaultValue={defaults?.unit ?? "COUNT"}>{metricUnits.map((item) => <option key={item}>{item}</option>)}</Select>
    <Select label="Aggregation" name="aggregation" defaultValue={defaults?.aggregation ?? "SUM"}>{metricAggregations.map((item) => <option key={item}>{item}</option>)}</Select>
    <Field label="Freshness (days)" name="freshnessDays" type="number" min={1} defaultValue={defaults?.freshnessDays ?? ""} />
    <div className="sm:col-span-2"><TextArea label="Definition (what exactly counts)" name="definition" rows={2} required defaultValue={defaults?.definition} /></div>
    <TextArea label="Numerator definition (RATE/COHORT)" name="numeratorDefinition" rows={2} defaultValue={defaults?.numeratorDefinition ?? ""} />
    <TextArea label="Denominator definition (RATE/COHORT)" name="denominatorDefinition" rows={2} defaultValue={defaults?.denominatorDefinition ?? ""} />
    <TextArea label="Cohort basis (COHORT)" name="cohortBasis" rows={2} defaultValue={defaults?.cohortBasis ?? ""} />
  </>;
}

export default async function ScorecardsPage({ searchParams }: { searchParams: Promise<{ brand?: string; correct?: string; saved?: string; error?: string }> }) {
  const [query, user] = await Promise.all([searchParams, requireCommandCenterUser()]);
  const brandFilter = query.brand || undefined;
  const now = new Date();
  const editable = canEditGrowth(user.role);
  const [brands, definitions, measurements, campaigns, progress, correcting] = await Promise.all([
    prisma.brand.findMany({ where: { active: true }, orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.growthMetricDefinition.findMany({ where: { brandId: brandFilter }, include: { brand: { select: { name: true } }, supersededBy: { select: { id: true } } }, orderBy: [{ brandId: "asc" }, { key: "asc" }, { version: "desc" }] }),
    prisma.growthMeasurement.findMany({ where: { brandId: brandFilter }, include: { definition: { select: { key: true, label: true, version: true, unit: true, freshnessDays: true } }, brand: { select: { name: true } }, campaign: { select: { name: true } }, activation: { select: { name: true } }, enteredBy: { select: { name: true, email: true } }, reviewedBy: { select: { name: true, email: true } }, supersededBy: { select: { id: true } } }, orderBy: [{ asOfAt: "desc" }, { createdAt: "desc" }], take: 60 }),
    prisma.campaign.findMany({ where: { status: { in: ["ACTIVE", "PLANNING", "PAUSED", "COMPLETE"] }, ...(brandFilter ? { brands: { some: { id: brandFilter } } } : {}) }, orderBy: { name: "asc" }, select: { id: true, name: true, activations: { select: { id: true, name: true }, orderBy: { name: "asc" } } } }),
    loadTargetProgress({ campaign: { status: "ACTIVE" }, ...(brandFilter ? { brandId: brandFilter } : {}) }, now),
    query.correct ? prisma.growthMeasurement.findUnique({ where: { id: query.correct }, include: { definition: { select: { label: true, version: true } }, supersededBy: { select: { id: true } } } }) : null,
  ]);
  const activeDefinitions = definitions.filter((definition) => definition.status === "ACTIVE");
  const returnTo = `/command-center/scorecards${brandFilter ? `?brand=${brandFilter}` : ""}`;
  const correction = correcting && !correcting.supersededBy ? correcting : null;

  return <div className="max-w-6xl">
    <p className="text-[10px] uppercase tracking-[.16em] text-[#747976]">Intelligence</p>
    <div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="font-display text-3xl text-white">Scorecards</h1><p className="mt-2 max-w-3xl text-sm text-[#8f9391]">Versioned metric definitions and source-cited measurements. Missing data stays UNKNOWN (never zero). Only reviewed measurements count toward targets; percentages are pooled, never summed.</p></div>
      <form className="flex items-end gap-2"><Select label="Brand" name="brand" defaultValue={brandFilter ?? ""}><option value="">All brands</option>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</Select><button className="rounded-lg border border-white/10 px-3 py-2.5 text-xs text-white">Filter</button></form></div>
    <FormNotice saved={query.saved} error={query.error} />

    <section className="mt-8"><h2 className="font-display text-xl text-white">Active campaign targets</h2>
      {progress.length ? <div className="mt-4 overflow-x-auto rounded-2xl border border-white/8"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/[.03] text-[10px] uppercase tracking-[.12em] text-[#747976]"><tr><th className="p-3">Campaign</th><th className="p-3">Metric</th><th className="p-3">Period (CT)</th><th className="p-3">Actual</th><th className="p-3">Target</th><th className="p-3">Freshness</th></tr></thead><tbody>{progress.map((row) => <tr key={row.id} className="border-t border-white/6"><td className="p-3"><Link href={`/command-center/campaigns/${row.campaignId}`} className="text-white hover:text-[#b8d4c8]">{row.campaignName}</Link><small className="block text-[#747976]">{row.brandName}{row.activationName ? ` · ${row.activationName}` : " · campaign-level"}</small></td><td className="p-3 text-[#d4d7d5]">{row.definition.label}<small className="block text-[#747976]">{row.definition.key} v{row.definition.version} · {row.definition.aggregation}</small></td><td className="p-3 text-xs text-[#8f9391]">{formatCentralDate(row.periodStart)} – {formatCentralDate(exclusiveEndToInclusive(row.periodEnd))}</td><td className="p-3"><span className={row.actual.status === "UNKNOWN" ? "text-[#a6a9ff]" : "text-white"}>{formatMetricValue(row.actual.value, row.definition.unit)}</span>{row.actual.pendingReview > 0 && <small className="block text-[#f0bd65]">{row.actual.pendingReview} awaiting review</small>}</td><td className="p-3 text-[#d4d7d5]">{formatMetricValue(row.targetValue, row.definition.unit)}{row.baselineValue !== null && <small className="block text-[#747976]">baseline {formatMetricValue(row.baselineValue, row.definition.unit)}</small>}</td><td className="p-3 text-xs">{row.actual.asOfAt ? <span className={row.stale ? "text-[#ec7f72]" : "text-[#8f9391]"}>{row.stale ? "Stale · " : ""}as of {formatCentralDate(row.actual.asOfAt)}</span> : <span className="text-[#747976]">No reviewed data</span>}</td></tr>)}</tbody></table></div> : <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-6 text-sm text-[#777b78]">No targets on active campaigns. Add targets from a campaign page once a metric definition is active.</p>}
    </section>

    <section className="mt-10"><h2 className="font-display text-xl text-white">Metric definitions</h2>
      {definitions.length ? <div className="mt-4 space-y-3">{definitions.map((definition) => <div key={definition.id} className="rounded-2xl border border-white/8 bg-[#101214] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-white">{definition.label} <span className="text-[#747976]">· {definition.brand.name} · {definition.key} v{definition.version}</span> <span className={`ml-1 text-[10px] ${definitionTone[definition.status]}`}>{definition.status}</span></p><p className="mt-1 text-xs text-[#8f9391]">{definition.funnelStage} · {definition.unit} · {definition.aggregation}{definition.freshnessDays ? ` · fresh for ${definition.freshnessDays}d` : ""} · effective {formatCentralDate(definition.effectiveAt)}</p><p className="mt-2 max-w-3xl text-xs text-[#b8bcba]">{definition.definition}</p>{(definition.numeratorDefinition || definition.denominatorDefinition) && <p className="mt-1 text-xs text-[#747976]">{definition.numeratorDefinition} ÷ {definition.denominatorDefinition}</p>}</div>
        {editable && <div className="flex gap-2">{definition.status === "DRAFT" && <form action={setMetricDefinitionStatusAction.bind(null, definition.id)}><input type="hidden" name="status" value="ACTIVE" /><button className="rounded-lg bg-[#b8d4c8] px-3 py-1.5 text-xs font-semibold text-[#07100c]">Activate</button></form>}{definition.status === "ACTIVE" && <form action={setMetricDefinitionStatusAction.bind(null, definition.id)}><input type="hidden" name="status" value="RETIRED" /><button className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-[#8f9391]">Retire</button></form>}</div>}</div>
        {editable && !definition.supersededBy && <details className="mt-3"><summary className="cursor-pointer text-xs text-[#b8d4c8]">New version (keeps history; activate to replace v{definition.version})</summary><form action={createMetricDefinitionVersionAction.bind(null, definition.id)} className="mt-3 grid gap-3 sm:grid-cols-3"><DefinitionFields defaults={definition} /><div className="sm:col-span-3"><SubmitButton>Create v{definition.version + 1} draft</SubmitButton></div></form></details>}
      </div>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-6 text-sm text-[#777b78]">No metric definitions yet. Define what a metric means before recording any numbers.</p>}
      {editable && <details className="mt-4 rounded-2xl border border-white/8 bg-[#101214] p-5" open={!definitions.length}><summary className="cursor-pointer font-display text-lg text-white">+ New metric definition</summary><form action={createMetricDefinitionAction} className="mt-4 grid gap-3 sm:grid-cols-3"><Select label="Brand" name="brandId" required defaultValue={brandFilter ?? ""}><option value="">Select brand</option>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</Select><DefinitionFields /><div className="sm:col-span-3"><SubmitButton>Create draft definition</SubmitButton></div></form></details>}
    </section>

    {editable && <section id="record" className="mt-10 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-xl text-white">{correction ? `Correct measurement (${correction.definition.label} v${correction.definition.version})` : "Record measurement"}</h2><p className="mt-1 text-xs text-[#747976]">{correction ? "The correction supersedes the original, which stays in history." : "Leave value blank to record an explicit UNKNOWN. For RATE metrics enter numerator and denominator; the percent is derived."} Dates are inclusive Central dates.</p>
      {activeDefinitions.length || correction ? <form action={recordMeasurementAction} className="mt-5 grid gap-3 sm:grid-cols-3">
        <input type="hidden" name="returnTo" value={returnTo} />
        {correction && <input type="hidden" name="supersedesId" value={correction.id} />}
        {correction ? <input type="hidden" name="definitionId" value={correction.definitionId} /> : <Select label="Metric (ACTIVE)" name="definitionId" required><option value="">Select metric</option>{activeDefinitions.map((definition) => <option key={definition.id} value={definition.id}>{definition.brand.name} · {definition.label} (v{definition.version}, {definition.unit})</option>)}</Select>}
        <Field label="Period start" name="periodStart" type="date" required defaultValue={toCentralDateInputValue(correction?.periodStart)} />
        <Field label="Period end (inclusive)" name="periodEnd" type="date" required defaultValue={correction ? toCentralDateInputValue(exclusiveEndToInclusive(correction.periodEnd)) : ""} />
        <Field label="Value" name="value" inputMode="decimal" defaultValue={correction ? num(correction.value) ?? "" : ""} />
        <Field label="Numerator" name="numerator" inputMode="decimal" defaultValue={correction ? num(correction.numerator) ?? "" : ""} />
        <Field label="Denominator" name="denominator" inputMode="decimal" defaultValue={correction ? num(correction.denominator) ?? "" : ""} />
        <Field label="As of (CT)" name="asOfAt" type="datetime-local" defaultValue={toCentralInputValue(now)} />
        <Field label="Source *" name="source" required placeholder="e.g. Supabase signups export" defaultValue={correction?.source ?? ""} />
        <Field label="Source URL" name="sourceUrl" type="url" defaultValue={correction?.sourceUrl ?? ""} />
        {correction ? <><input type="hidden" name="campaignId" value={correction.campaignId ?? ""} /><input type="hidden" name="activationId" value={correction.activationId ?? ""} /></> : <><Select label="Campaign (optional)" name="campaignId"><option value="">Brand-level</option>{campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</Select><Select label="Activation (optional)" name="activationId"><option value="">Campaign-level</option>{campaigns.flatMap((campaign) => campaign.activations.map((activation) => <option key={activation.id} value={activation.id}>{campaign.name} — {activation.name}</option>))}</Select></>}
        <Field label="Scope" name="scope" placeholder="e.g. Dallas" defaultValue={correction?.scope ?? ""} readOnly={Boolean(correction)} />
        <Field label="Cohort key" name="cohortKey" defaultValue={correction?.cohortKey ?? ""} readOnly={Boolean(correction)} />
        <Field label="External key (dedupe)" name="externalKey" />
        <div className="sm:col-span-3"><TextArea label="Notes" name="notes" rows={2} /></div>
        <div className="flex items-center gap-3 sm:col-span-3"><SubmitButton>{correction ? "Record correction" : "Record measurement"}</SubmitButton>{correction && <Link href={returnTo} className="text-xs text-[#8f9391]">Cancel correction</Link>}</div>
      </form> : <p className="mt-4 text-sm text-[#777b78]">Activate a metric definition before recording measurements.</p>}
    </section>}

    <section className="mt-10"><h2 className="font-display text-xl text-white">Recent measurements</h2>
      {measurements.length ? <div className="mt-4 overflow-x-auto rounded-2xl border border-white/8"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/[.03] text-[10px] uppercase tracking-[.12em] text-[#747976]"><tr><th className="p-3">Metric</th><th className="p-3">Period (CT)</th><th className="p-3">Value</th><th className="p-3">Status</th><th className="p-3">Source</th><th className="p-3">Attribution</th><th className="p-3" /></tr></thead><tbody>{measurements.map((row) => { const superseded = Boolean(row.supersededBy); return <tr key={row.id} className={`border-t border-white/6 ${superseded ? "opacity-50" : ""}`}><td className="p-3 text-white">{row.definition.label}<small className="block text-[#747976]">{row.brand.name} · v{row.definition.version}</small></td><td className="p-3 text-xs text-[#8f9391]">{formatCentralDate(row.periodStart)} – {formatCentralDate(exclusiveEndToInclusive(row.periodEnd))}<small className="block">as of {formatCentralDateTime(row.asOfAt)}</small></td><td className="p-3"><span className={row.value === null ? "text-[#a6a9ff]" : "text-white"}>{formatMetricValue(num(row.value), row.definition.unit)}</span>{row.denominator !== null && <small className="block text-[#747976]">{num(row.numerator)} / {num(row.denominator)}</small>}</td><td className="p-3 text-xs"><span className={measurementTone[row.status]}>{superseded ? "SUPERSEDED" : row.status}</span>{row.supersedesId && <small className="block text-[#747976]">correction</small>}<small className="block text-[#747976]">by {row.enteredBy?.name || row.enteredBy?.email || "unknown"}{row.reviewedAt ? ` · reviewed by ${row.reviewedBy?.name || row.reviewedBy?.email || "unknown"}` : ""}</small></td><td className="p-3 text-xs text-[#b8bcba]">{row.sourceUrl ? <a href={row.sourceUrl} target="_blank" rel="noreferrer" className="text-[#b8d4c8] underline-offset-2 hover:underline">{row.source}</a> : row.source}</td><td className="p-3 text-xs text-[#8f9391]">{row.campaign?.name ?? "Brand-level"}{row.activation ? ` · ${row.activation.name}` : ""}{row.scope ? ` · ${row.scope}` : ""}{row.cohortKey ? ` · cohort ${row.cohortKey}` : ""}</td><td className="p-3 text-right">{editable && !superseded && <div className="flex justify-end gap-2">{!row.reviewedAt && <form action={reviewMeasurementAction.bind(null, row.id)}><input type="hidden" name="returnTo" value={returnTo} /><button className="rounded-lg border border-[#87d2ac]/30 px-2.5 py-1 text-xs text-[#87d2ac]">Review</button></form>}<Link href={`${returnTo}${returnTo.includes("?") ? "&" : "?"}correct=${row.id}#record`} className="rounded-lg border border-white/10 px-2.5 py-1 text-xs text-[#b8bcba]">Correct</Link></div>}</td></tr>; })}</tbody></table></div> : <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-6 text-sm text-[#777b78]">No measurements recorded.</p>}
    </section>
  </div>;
}
