import Link from "next/link";
import { AiLabForm } from "@/components/command-center/ai-lab-form";
import { PageHeader } from "@/components/command-center/page-header";
import { createDraftFromExecutionAction } from "@/lib/ai-lab/actions";
import { getAiProviderAvailability } from "@/lib/ai-lab/provider";
import { generatedExecutionSchema } from "@/lib/ai-lab/schema";
import { resolveAiLabSetupDefaults } from "@/lib/ai-lab/setup-defaults";
import { hasConfiguredBrandBrain } from "@/lib/command-center/brand-brain";
import { prisma } from "@/lib/prisma";

function stringValue(value: unknown) { return typeof value === "string" ? value : ""; }

export default async function AiLabPage({ searchParams }: { searchParams: Promise<{ run?: string; brand?: string; opportunity?: string; event?: string; growthProgram?: string; campaign?: string; activation?: string }> }) {
  const { run: selectedRunId, brand: defaultBrandId, opportunity: defaultOpportunityId, event: defaultEventId, growthProgram: defaultGrowthProgramId, campaign: defaultCampaignId, activation: defaultActivationId } = await searchParams;
  const [allBrands, programs, campaigns, activations, events, opportunities, relationships, runs, selectedRun] = await Promise.all([
    prisma.brand.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.growthProgram.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.campaign.findMany({ where: { active: true }, orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.campaignActivation.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.growthEvent.findMany({ where: { league: "NFL" }, orderBy: { startsAt: "asc" }, take: 300, select: { id: true, name: true } }),
    prisma.opportunity.findMany({ where: { status: { not: "DISMISSED" } }, orderBy: { updatedAt: "desc" }, take: 100, select: { id: true, title: true, eventId: true, activation: { select: { id: true, campaign: { select: { id: true, programId: true } } } }, campaigns: { select: { campaign: { select: { id: true, programId: true } } }, orderBy: { campaignId: "asc" } } } }),
    prisma.relationship.findMany({ orderBy: { updatedAt: "desc" }, take: 100, select: { id: true, name: true } }),
    prisma.generationRun.findMany({ include: { brand: { select: { name: true } }, content: { select: { id: true } } }, orderBy: { createdAt: "desc" }, take: 20 }),
    selectedRunId ? prisma.generationRun.findUnique({ where: { id: selectedRunId }, include: { brand: { select: { name: true } }, event: { select: { name: true } }, opportunity: { select: { title: true } }, content: { select: { id: true } }, createdBy: { select: { name: true, email: true } } } }) : null,
  ]);
  const brands = allBrands.filter(hasConfiguredBrandBrain).map(({ id, name }) => ({ id, name }));
  const provider = getAiProviderAvailability();
  const setupDefaults = resolveAiLabSetupDefaults({ brandId: defaultBrandId, opportunityId: defaultOpportunityId, eventId: defaultEventId, growthProgramId: defaultGrowthProgramId, campaignId: defaultCampaignId, activationId: defaultActivationId, opportunities });
  const parsedOutput = selectedRun?.structuredOutput ? generatedExecutionSchema.safeParse(selectedRun.structuredOutput) : null;
  const output = parsedOutput?.success ? parsedOutput.data : null;
  const context = selectedRun?.resolvedContext as Record<string, unknown> | undefined;
  const trust = context?.trust as Record<string, unknown> | undefined;
  const canCreateDraft = selectedRun?.status === "SUCCEEDED" && selectedRun.recommendation === "CREATE" && selectedRun.opportunityId && !selectedRun.contentId;

  return <div><PageHeader title="AI Lab" description="Resolve trusted SNG context, generate one structured marketing execution, and optionally hand a qualified result to the existing Content Queue." />
    {!provider.configured && <div className="mt-7 rounded-2xl border border-[#f0bd65]/25 bg-[#f0bd65]/5 p-5"><p className="text-sm font-semibold text-[#e2c58f]">Generation is currently unavailable</p><p className="mt-1 text-xs leading-5 text-[#a99a7e]">Configure the server-only OPENAI_API_KEY and AI_MODEL environment variables. The rest of the Command Center remains available.</p></div>}
    <section className="mt-7 rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#b8d4c8]">Generation Setup</p><h2 className="mt-2 font-display text-xl text-white">Build a brand-specific execution</h2></div><span className="text-xs text-[#747976]">{brands.length} configured Brands</span></div><AiLabForm brands={brands} programs={programs} campaigns={campaigns} activations={activations} events={events} opportunities={opportunities.map(({ id, title }) => ({ id, name: title }))} relationships={relationships} disabled={!provider.configured} defaults={setupDefaults} /></section>

    {selectedRun && <section className="mt-8 space-y-5">
      <div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#b8d4c8]">Run Detail</p><h2 className="mt-2 font-display text-2xl text-white">{selectedRun.brand?.name || "Historical run"}</h2><p className="mt-1 text-xs text-[#747976]">{selectedRun.createdAt.toLocaleString()} · {selectedRun.channel.replaceAll("_", " ")}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#b8bcba]">{selectedRun.status}</span></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Generation version", selectedRun.generationVersion], ["Provider / model", [selectedRun.provider, selectedRun.model].filter(Boolean).join(" / ") || "Not resolved"], ["Event", selectedRun.event?.name || "None"], ["Opportunity", selectedRun.opportunity?.title || "None"], ["Created by", selectedRun.createdBy?.name || selectedRun.createdBy?.email || "Historical user"]].map(([label, value]) => <div key={label} className="rounded-xl bg-white/[.025] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">{label}</p><p className="mt-2 text-sm text-white">{value}</p></div>)}</div>
        {selectedRun.errorMessage && <p className="mt-5 rounded-xl border border-[#ec7f72]/25 bg-[#ec7f72]/5 p-4 text-sm text-[#ec9a90]">{selectedRun.errorMessage}</p>}
      </div>
      <details className="rounded-2xl border border-white/8 bg-[#101214] p-6" open><summary className="cursor-pointer font-display text-xl text-white">Resolved Context</summary><div className="mt-4 grid gap-4 md:grid-cols-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">Structured records</p><p className="mt-2 text-sm text-[#d4d7d5]">{stringValue(trust?.structuredContext) || "Trusted structured context"}</p></div><div><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">Operator context</p><p className="mt-2 text-sm text-[#d4d7d5]">{stringValue(trust?.operatorContext) || "Absent"}</p></div><div><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">Absent context</p><p className="mt-2 text-sm text-[#d4d7d5]">{stringValue(trust?.absentContext)}</p></div></div><pre className="mt-5 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-[#080a0b] p-4 text-xs leading-5 text-[#a9aeab]">{JSON.stringify(context, null, 2)}</pre></details>
      {output && <article className="rounded-2xl border border-[#b8d4c8]/20 bg-[#101714] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#b8d4c8]">Structured Result</p><h2 className="mt-2 font-display text-2xl text-white">{output.recommendation.replaceAll("_", " ")}</h2></div>{selectedRun.contentId ? <Link className="rounded-lg border border-white/10 px-4 py-2 text-sm text-white" href={`/command-center/queue/${selectedRun.contentId}/edit`}>Open Draft</Link> : canCreateDraft ? <form action={createDraftFromExecutionAction.bind(null, selectedRun.id)}><button className="rounded-lg bg-[#b8d4c8] px-4 py-2 text-sm font-semibold text-[#07100c]">Create Draft</button></form> : null}</div>
        <p className="mt-5 text-sm leading-6 text-[#d4d7d5]">{output.reason}</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{[["Why now", output.whyNow], ["Editorial angle", output.editorialAngle], ["Draft copy", output.draftCopy], ["Visual brief", output.visualBrief], ["CTA", output.cta], ["Channel / timing", `${output.recommendedChannel.replaceAll("_", " ")} · ${output.timing}`]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/7 bg-black/20 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#d4d7d5]">{value || "Not applicable"}</p></div>)}</div>
        <div className="mt-5 grid gap-4 md:grid-cols-3">{[["Evidence used", output.evidenceUsed], ["Assumptions", output.assumptions], ["Warnings", output.warnings]].map(([label, items]) => <div key={label as string}><p className="text-xs font-semibold text-white">{label as string}</p><ul className="mt-2 space-y-2 text-xs leading-5 text-[#8f9391]">{(items as string[]).length ? (items as string[]).map((item) => <li key={item}>• {item}</li>) : <li>None</li>}</ul></div>)}</div>
        {output.recommendation === "CREATE" && !selectedRun.opportunityId && <p className="mt-5 rounded-xl border border-[#f0bd65]/20 bg-[#f0bd65]/5 p-4 text-xs text-[#e2c58f]">This is a valid generation result, but Create Draft is unavailable because no existing Opportunity was selected. AI Lab will not fabricate one.</p>}
      </article>}
    </section>}

    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#b8d4c8]">History</p><h2 className="mt-2 font-display text-xl text-white">Recent Runs</h2></div><span className="text-xs text-[#747976]">Last 20</span></div><div className="mt-4 overflow-hidden rounded-2xl border border-white/8">{runs.map((run) => <Link key={run.id} href={`/command-center/ai-lab?run=${run.id}`} className="grid gap-2 border-t border-white/7 bg-[#101214] px-5 py-4 first:border-t-0 hover:bg-white/[.025] sm:grid-cols-[1.2fr_.8fr_.8fr_.7fr]"><span className="text-sm text-white">{run.brand?.name || "Deleted Brand"}<small className="mt-1 block text-[#747976]">{run.createdAt.toLocaleString()}</small></span><span className="text-xs text-[#a5aaa7]">{run.channel.replaceAll("_", " ")}</span><span className="text-xs text-[#b8d4c8]">{run.recommendation?.replaceAll("_", " ") || run.status}</span><span className="text-xs text-[#747976]">{run.content ? "Draft created" : run.generationVersion}</span></Link>)}{!runs.length && <p className="bg-[#101214] p-8 text-center text-sm text-[#777b78]">No generation runs yet.</p>}</div></section>
  </div>;
}
