import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckboxGroup, Field, Select, SubmitButton, TextArea } from "@/components/command-center/form-fields";
import { FormNotice } from "@/components/command-center/form-notice";
import { requireCommandCenterUser } from "@/lib/auth/session";
import { addRelationshipActivity, updateRelationshipStage } from "@/lib/command-center/actions";
import { canEditGrowth } from "@/lib/growth/permissions";
import { updateRelationshipOperatingAction } from "@/lib/growth/server-actions";
import { calendarDayKey, formatCalendarDay, formatCentralDateTime } from "@/lib/growth/time";
import { prisma } from "@/lib/prisma";

export default async function RelationshipDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ id }, notice, user] = await Promise.all([params, searchParams, requireCommandCenterUser()]);
  const [item, campaigns, activations, users] = await Promise.all([prisma.relationship.findUnique({ where: { id }, include: { organization: { include: { market: true, teams: true } }, contact: true, owner: true, campaign: true, campaignLinks: { include: { campaign: true } }, relevantBrands: true, activations: true, growthActions: { where: { status: { in: ["OPEN", "IN_PROGRESS", "BLOCKED"] } }, orderBy: { createdAt: "desc" } }, activities: { include: { campaign: true, activation: true }, orderBy: { occurredAt: "desc" } } } }), prisma.campaign.findMany({ where: { status: { in: ["PLANNING", "ACTIVE", "PAUSED"] } }, orderBy: { name: "asc" } }), prisma.campaignActivation.findMany({ where: { status: { in: ["PLANNED", "READY", "ACTIVE"] } }, include: { campaign: true }, orderBy: { name: "asc" } }), prisma.user.findMany({ select: { id: true, name: true, email: true }, orderBy: { email: "asc" } })]);
  if (!item) notFound();
  const editable = canEditGrowth(user.role);
  const linkedCampaigns = new Map(item.campaignLinks.map((link) => [link.campaignId, link.campaign]));
  if (item.campaign && !linkedCampaigns.has(item.campaign.id)) linkedCampaigns.set(item.campaign.id, item.campaign);
  const campaignChoices = [...new Map([...campaigns, ...linkedCampaigns.values()].map((campaign) => [campaign.id, { id: campaign.id, name: campaign.name }])).values()];

  return <div><Link href="/command-center/relationships" className="text-xs text-[#b8d4c8]">← Relationship Pipeline</Link>
    <div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs text-[#747976]">{item.organization.type} · {item.organization.market?.name || "No market"}</p><h1 className="mt-2 font-display text-3xl text-white">{item.organization.name}</h1><p className="mt-2 text-sm text-[#929795]">{item.contact ? `${item.contact.name}${item.contact.title ? ` · ${item.contact.title}` : ""}` : "No contact set"}</p></div>{editable ? <form action={updateRelationshipStage.bind(null, item.id)} className="flex items-end gap-2"><Select label="Stage" name="stage" defaultValue={item.stage}>{["PROSPECT","CONTACTED","CONVERSATION","OPPORTUNITY","PARTNER","CLOSED","NOT_PURSUING"].map((x) => <option key={x}>{x}</option>)}</Select><button className="rounded-lg border border-white/10 px-3 py-2.5 text-xs text-white">Move</button></form> : <p className="self-end text-xs text-[#8f9391]">{item.stage.replaceAll("_", " ")}</p>}</div>
    <FormNotice saved={notice.saved} error={notice.error} />

    <section className="mt-7 grid gap-4 lg:grid-cols-4">
      <div className="rounded-2xl border border-[#b8d4c8]/20 bg-[#101214] p-5 lg:col-span-2"><p className="text-xs text-[#747976]">Next action</p><p className={`mt-3 text-sm ${item.nextAction ? "text-white" : "text-[#f0bd65]"}`}>{item.nextAction || "No next action set"}</p><p className="mt-2 text-xs text-[#747976]">Due {formatCalendarDay(item.nextFollowUpAt, "unscheduled")} · Owner {item.owner?.name || item.owner?.email || "unassigned"}</p></div>
      <div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Campaigns</p><p className="mt-3 text-sm text-white">{[...linkedCampaigns.values()].map((campaign) => campaign.name).join(" · ") || "None"}</p></div>
      <div className="rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Brands / teams</p><p className="mt-3 text-sm text-white">{item.relevantBrands.map((x) => x.name).join(" · ") || "No brands"}</p><p className="mt-2 text-xs text-[#747976]">{item.organization.teams.map((x) => x.name).join(" · ") || "No teams"}{item.activations.length ? ` · ${item.activations.map((x) => x.name).join(" · ")}` : ""}</p></div>
    </section>

    <section className="mt-5 grid gap-4 md:grid-cols-3">{[["Fit", item.fitReason], ["Offer", item.offer], ["Audience", item.audience], ["Priority", item.priority ? `${item.priority}${item.priorityEvidence ? ` — ${item.priorityEvidence}` : ""}` : null], ["Commitment", item.commitment], ["Outcome", item.outcome]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/7 bg-[#0d0f10] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-[#747976]">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm text-[#d4d7d5]">{value || "—"}</p></div>)}</section>

    {item.growthActions.length > 0 && <section className="mt-5 rounded-2xl border border-white/8 bg-[#101214] p-5"><p className="text-xs text-[#747976]">Linked growth actions (separate work items, not the relationship&apos;s next action)</p><ul className="mt-3 space-y-2">{item.growthActions.map((action) => <li key={action.id} className="text-sm text-white">{action.title} <span className="text-xs text-[#747976]">· {action.status.replaceAll("_", " ")}{action.blocker ? ` — ${action.blocker}` : ""}</span></li>)}</ul></section>}

    {editable && <details className="mt-5 rounded-2xl border border-white/8 bg-[#101214] p-6"><summary className="cursor-pointer font-display text-lg text-white">Edit operating fields</summary><form action={updateRelationshipOperatingAction.bind(null, item.id)} className="mt-5 grid gap-4 sm:grid-cols-2">
      <div className="sm:col-span-2"><Field label="Next action" name="nextAction" defaultValue={item.nextAction ?? ""} placeholder="The single next thing we will do" /></div>
      <Field label="Next action due (CT)" name="nextFollowUpAt" type="date" defaultValue={calendarDayKey(item.nextFollowUpAt)} />
      <Select label="Owner" name="ownerId" defaultValue={item.ownerId ?? ""}><option value="">Unassigned</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name || u.email}</option>)}</Select>
      <TextArea label="Why they fit" name="fitReason" rows={2} defaultValue={item.fitReason ?? ""} />
      <TextArea label="Offer to them" name="offer" rows={2} defaultValue={item.offer ?? ""} />
      <TextArea label="Their audience" name="audience" rows={2} defaultValue={item.audience ?? ""} />
      <div className="grid gap-4"><Select label="Priority" name="priority" defaultValue={item.priority ?? ""}><option value="">Not set</option>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((p) => <option key={p}>{p}</option>)}</Select><Field label="Priority evidence" name="priorityEvidence" defaultValue={item.priorityEvidence ?? ""} /></div>
      <TextArea label="Commitment (what they agreed to)" name="commitment" rows={2} defaultValue={item.commitment ?? ""} />
      <TextArea label="Outcome" name="outcome" rows={2} defaultValue={item.outcome ?? ""} />
      <div className="sm:col-span-2"><p className="mb-2 text-xs text-[#747976]">Campaigns</p><CheckboxGroup name="campaignIds" items={campaignChoices} selectedIds={[...linkedCampaigns.keys()]} /></div>
      <div><SubmitButton>Save operating fields</SubmitButton></div>
    </form></details>}

    <section className="mt-7 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><div className="rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Activity timeline</h2><div className="mt-5 space-y-4">{item.activities.map((activity) => <div key={activity.id} className="border-l border-[#b8d4c8]/30 pl-4"><p className="text-xs text-[#b8d4c8]">{activity.executionType?.replaceAll("_", " ") || activity.type} · {activity.direction ? activity.direction.toLowerCase() : "direction unknown"} · {formatCentralDateTime(activity.occurredAt)}</p><p className="mt-1 text-sm text-white">{activity.summary}</p>{(activity.campaign || activity.activation) && <p className="mt-1 text-xs text-[#747976]">{activity.campaign?.name}{activity.activation ? ` → ${activity.activation.name}` : ""}</p>}{activity.nextStep && <p className="mt-1 text-xs text-[#8f9391]">Next: {activity.nextStep}</p>}</div>)}{!item.activities.length && <p className="text-sm text-[#777b78]">No activity recorded yet.</p>}</div></div>
      {editable && <form action={addRelationshipActivity.bind(null, item.id)} className="space-y-4 rounded-2xl border border-white/8 bg-[#101214] p-6"><h2 className="font-display text-lg text-white">Log activity</h2><div className="grid gap-4 sm:grid-cols-3"><Select label="Activity" name="type">{["EMAIL","DM","CALL","MEETING","NOTE","FOLLOW_UP","OTHER"].map((x) => <option key={x}>{x}</option>)}</Select><Select label="Direction" name="direction" defaultValue="OUTBOUND"><option value="OUTBOUND">Outbound (we reached out)</option><option value="INBOUND">Inbound (they responded)</option><option value="INTERNAL">Internal note</option></Select><Select label="Execution type" name="executionType"><option value="">Not classified</option>{["ORGANIC_SOCIAL","CREATOR_OUTREACH","MEDIA_OUTREACH","COMMUNITY","PARTNERSHIP","PAID","PRODUCT_EVENT","OTHER"].map((x) => <option key={x}>{x}</option>)}</Select></div><Select label="Campaign" name="campaignId"><option value="">No campaign</option>{campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</Select><Select label="Activation" name="activationId"><option value="">No activation</option>{activations.map((activation) => <option key={activation.id} value={activation.id}>{activation.campaign.name} → {activation.name}</option>)}</Select><Field label="Date (CT)" name="occurredAt" type="datetime-local" /><TextArea label="What happened?" name="summary" rows={4} required /><Field label="Next step (on this activity)" name="nextStep" /><Field label="Update relationship next action (optional)" name="nextAction" /><Field label="Next action due (CT, optional — blank keeps current)" name="nextFollowUpAt" type="date" /><SubmitButton>Save activity</SubmitButton></form>}</section></div>;
}
